import { Product } from "./store";

export const birdsAndFishCategory = {
  id: "birds-fish",
  name: "Birds & Fish",
  slug: "birds-fish",
  image: "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800",
  description: "Premium birds and aquarium fish collection",
  featured: true,
  subcategories: [
    { name: "Birds", slug: "birds" },
    { name: "Freshwater Fish", slug: "freshwater-fish" },
    { name: "Marine Fish", slug: "marine-fish" },
    { name: "Fish Accessories", slug: "fish-accessories" },
  ],
};

export const birdSpecies = [
  "Budgerigar", "Cockatiel", "Lovebird", "Finch", "Canary", "Conure", 
  "Parrotlet", "Indian Ringneck", "Cockatoo", "African Grey", "Caique", "Lorikeet"
];

export const freshwaterFishSpecies = [
  "Guppy", "Molly", "Platy", "Swordtail", "Tetra", "Goldfish", "Betta", 
  "Angelfish", "Discus", "Corydoras", "Pleco", "Danio", "Barb", "Rainbowfish", "Gourami"
];

export const marineFishSpecies = [
  "Clownfish", "Royal Gramma", "Banggai Cardinal", "Tangs", "Firefish", "Chromis", "Damselfish"
];

export const birdsAndFishProducts: Product[] = [
  // ═══════════════════ BIRDS ═══════════════════
  {
    id: "bird-budgie-1",
    name: "Budgerigar (Budgie)",
    slug: "budgerigar-budgie",
    category: "birds-fish",
    subcategory: "birds",
    price: 499,
    originalPrice: 699,
    images: [
      "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800",
      "https://images.unsplash.com/photo-1544923408-75c5cef46f14?w=800",
    ],
    description: "Adorable and playful Budgerigar, one of the most popular pet birds worldwide. Known for their ability to mimic speech and cheerful personalities. Perfect for beginners and experienced bird owners alike.",
    careGuide: "Cage: 18x18x18 inches minimum. Diet: Seeds, pellets, fresh fruits and vegetables. Lifespan: 5-10 years with proper care.",
    specifications: {
      "Size": "7-8 inches",
      "Lifespan": "5-10 years",
      "Noise Level": "Low to Moderate",
      "Temperament": "Friendly, Playful",
    },
    variants: [
      { name: "Color", options: ["Green", "Blue", "Yellow", "White", "Lutino", "Albino"] },
    ],
    inStock: true,
    isFeatured: true,
    rating: 4.8,
    reviews: 342,
    tags: ["bird", "budgie", "budgerigar", "beginner", "best-seller"],
  },
  {
    id: "bird-cockatiel-1",
    name: "Cockatiel",
    slug: "cockatiel",
    category: "birds-fish",
    subcategory: "birds",
    price: 1999,
    originalPrice: 2499,
    images: [
      "https://images.unsplash.com/photo-1591198936750-16d8e15edb9e?w=800",
    ],
    description: "Gentle and affectionate Cockatiel with distinctive crest feathers. Excellent whistlers and can learn tunes. Great companion birds that bond well with their owners.",
    careGuide: "Cage: 24x18x24 inches minimum. Diet: Pellets, seeds, fresh produce. Lifespan: 15-25 years.",
    specifications: {
      "Size": "12-13 inches",
      "Lifespan": "15-25 years",
      "Noise Level": "Moderate",
      "Temperament": "Gentle, Affectionate",
    },
    variants: [
      { name: "Variant", options: ["Normal Grey", "Lutino", "Pied", "Pearl", "Cinnamon"] },
    ],
    inStock: true,
    rating: 4.9,
    reviews: 256,
    tags: ["bird", "cockatiel", "crest", "whistler"],
  },
  {
    id: "bird-lovebird-1",
    name: "Lovebird",
    slug: "lovebird",
    category: "birds-fish",
    subcategory: "birds",
    price: 1499,
    originalPrice: 1899,
    images: [
      "https://images.unsplash.com/photo-1544923408-75c5cef46f14?w=800",
    ],
    description: "Colorful and energetic Lovebirds known for their strong pair bonds. Small but full of personality. Available in beautiful color mutations.",
    careGuide: "Cage: 24x18x24 inches. Diet: Seeds, pellets, fruits, vegetables. Lifespan: 10-15 years.",
    specifications: {
      "Size": "5-7 inches",
      "Lifespan": "10-15 years",
      "Noise Level": "Moderate",
      "Temperament": "Active, Social",
    },
    variants: [
      { name: "Species", options: ["Peach-faced", "Fischer's", "Masked", "Black-cheeked"] },
    ],
    inStock: true,
    rating: 4.7,
    reviews: 189,
    tags: ["bird", "lovebird", "colorful", "pair"],
  },
  {
    id: "bird-finch-1",
    name: "Zebra Finch & Gouldian Finch",
    slug: "zebra-gouldian-finch",
    category: "birds-fish",
    subcategory: "birds",
    price: 599,
    images: [
      "https://images.unsplash.com/photo-1452570053594-1b985d6ea890?w=800",
    ],
    description: "Beautiful finches perfect for aviaries. Zebra Finches are hardy and easy to care for, while Gouldian Finches display stunning rainbow colors. Best kept in pairs or groups.",
    careGuide: "Flight cage or aviary recommended. Diet: Finch seed mix, egg food. Lifespan: 5-8 years.",
    specifications: {
      "Size": "4-5 inches",
      "Lifespan": "5-8 years",
      "Noise Level": "Low",
      "Temperament": "Peaceful, Social",
    },
    variants: [
      { name: "Type", options: ["Zebra Finch", "Gouldian Finch"] },
    ],
    inStock: true,
    rating: 4.5,
    reviews: 145,
    tags: ["bird", "finch", "zebra", "gouldian", "aviary"],
  },
  {
    id: "bird-canary-1",
    name: "Canary",
    slug: "canary-bird",
    category: "birds-fish",
    subcategory: "birds",
    price: 1299,
    images: [
      "https://images.unsplash.com/photo-1591198936750-16d8e15edb9e?w=800",
    ],
    description: "Melodious Canary birds famous for their beautiful singing. Males are particularly known for their elaborate songs. Available in various color varieties.",
    careGuide: "Cage: 18x18x24 inches. Diet: Canary seed, greens, egg food. Lifespan: 10-15 years.",
    specifications: {
      "Size": "4-5 inches",
      "Lifespan": "10-15 years",
      "Noise Level": "Moderate (singing)",
      "Temperament": "Independent, Musical",
    },
    variants: [
      { name: "Variety", options: ["Red Factor", "Yellow", "Gloster", "Border"] },
    ],
    inStock: true,
    rating: 4.6,
    reviews: 167,
    tags: ["bird", "canary", "singing", "melodious"],
  },
  {
    id: "bird-conure-green-1",
    name: "Green-Cheeked Conure",
    slug: "green-cheeked-conure",
    category: "birds-fish",
    subcategory: "birds",
    price: 8999,
    originalPrice: 10999,
    images: [
      "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800",
    ],
    description: "Playful and cuddly Green-Cheeked Conure, one of the quieter conure species. Known for their acrobatic antics and loving personalities. Great apartment birds.",
    careGuide: "Cage: 24x24x30 inches. Diet: Pellets, fresh produce, nuts. Lifespan: 20-30 years.",
    specifications: {
      "Size": "10 inches",
      "Lifespan": "20-30 years",
      "Noise Level": "Low to Moderate",
      "Temperament": "Playful, Affectionate",
    },
    variants: [
      { name: "Mutation", options: ["Normal", "Pineapple", "Turquoise", "Yellow-sided"] },
    ],
    inStock: true,
    rating: 4.8,
    reviews: 123,
    tags: ["bird", "conure", "green-cheeked", "quiet"],
  },
  {
    id: "bird-sun-conure-1",
    name: "Sun Conure",
    slug: "sun-conure",
    category: "birds-fish",
    subcategory: "birds",
    price: 25000,
    originalPrice: 30000,
    images: [
      "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800",
    ],
    description: "Stunning Sun Conure with vibrant yellow, orange, and red plumage. Extremely social and affectionate. Known for their loud calls but incredibly loyal companions.",
    careGuide: "Cage: 30x30x36 inches. Diet: Pellets, fruits, vegetables, nuts. Lifespan: 25-30 years.",
    specifications: {
      "Size": "12 inches",
      "Lifespan": "25-30 years",
      "Noise Level": "High",
      "Temperament": "Social, Loud, Loving",
    },
    inStock: true,
    rating: 4.9,
    reviews: 89,
    tags: ["bird", "conure", "sun", "colorful", "loud"],
  },
  {
    id: "bird-parrotlet-1",
    name: "Parrotlet",
    slug: "parrotlet",
    category: "birds-fish",
    subcategory: "birds",
    price: 4999,
    images: [
      "https://images.unsplash.com/photo-1544923408-75c5cef46f14?w=800",
    ],
    description: "Tiny but mighty Parrotlets pack a big personality in a small package. These pocket parrots can learn to talk and are known for their bold, fearless nature.",
    careGuide: "Cage: 18x18x18 inches. Diet: Pellets, seeds, fresh foods. Lifespan: 15-20 years.",
    specifications: {
      "Size": "4-5 inches",
      "Lifespan": "15-20 years",
      "Noise Level": "Low",
      "Temperament": "Bold, Feisty",
    },
    variants: [
      { name: "Species", options: ["Pacific", "Green-rumped"] },
    ],
    inStock: true,
    rating: 4.7,
    reviews: 98,
    tags: ["bird", "parrotlet", "small", "talking"],
  },
  {
    id: "bird-ringneck-1",
    name: "Indian Ringneck Parakeet",
    slug: "indian-ringneck-parakeet",
    category: "birds-fish",
    subcategory: "birds",
    price: 12000,
    originalPrice: 15000,
    images: [
      "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800",
    ],
    description: "Elegant Indian Ringneck Parakeet known for exceptional talking ability. Males develop a distinctive neck ring. Available in stunning color mutations.",
    careGuide: "Cage: 24x24x36 inches. Diet: Pellets, seeds, fruits, vegetables. Lifespan: 25-30 years.",
    specifications: {
      "Size": "16 inches (including tail)",
      "Lifespan": "25-30 years",
      "Noise Level": "Moderate",
      "Temperament": "Intelligent, Independent",
    },
    variants: [
      { name: "Color", options: ["Blue", "Green", "Lutino", "Violet"] },
    ],
    inStock: true,
    rating: 4.8,
    reviews: 156,
    tags: ["bird", "ringneck", "indian", "talking", "parakeet"],
  },
  {
    id: "bird-african-grey-1",
    name: "African Grey Parrot (Congo & Timneh)",
    slug: "african-grey-parrot",
    category: "birds-fish",
    subcategory: "birds",
    price: 85000,
    originalPrice: 100000,
    images: [
      "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800",
    ],
    description: "The Einstein of parrots! African Grey Parrots are renowned for their incredible intelligence and ability to learn extensive vocabulary. Exceptional companions for dedicated owners.",
    careGuide: "Cage: 36x24x48 inches. Diet: High-quality pellets, nuts, fresh produce. Lifespan: 40-60 years. Requires significant mental stimulation.",
    specifications: {
      "Size": "12-14 inches",
      "Lifespan": "40-60 years",
      "Noise Level": "Moderate",
      "Temperament": "Intelligent, Sensitive",
    },
    variants: [
      { name: "Type", options: ["Congo African Grey", "Timneh African Grey"] },
    ],
    inStock: true,
    isNew: true,
    isFeatured: true,
    rating: 5.0,
    reviews: 67,
    tags: ["bird", "african-grey", "parrot", "talking", "intelligent", "new-arrival"],
  },
  {
    id: "bird-lorikeet-1",
    name: "Rainbow Lorikeet",
    slug: "rainbow-lorikeet",
    category: "birds-fish",
    subcategory: "birds",
    price: 35000,
    images: [
      "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800",
    ],
    description: "Spectacularly colorful Rainbow Lorikeet with vibrant blue, green, orange, and red plumage. Unique nectar-feeding diet. Playful and energetic personalities.",
    careGuide: "Cage: 36x24x36 inches. Diet: Specialized nectar/lorikeet diet, fresh fruits. Lifespan: 20-30 years. Messy feeders - easy-clean cage recommended.",
    specifications: {
      "Size": "10-12 inches",
      "Lifespan": "20-30 years",
      "Noise Level": "High",
      "Temperament": "Playful, Energetic",
    },
    inStock: true,
    isNew: true,
    rating: 4.9,
    reviews: 45,
    tags: ["bird", "lorikeet", "rainbow", "colorful", "nectar", "new-arrival"],
  },

  // ═══════════════════ FRESHWATER FISH ═══════════════════
  {
    id: "fish-guppy-1",
    name: "Fancy Guppy",
    slug: "fancy-guppy",
    category: "birds-fish",
    subcategory: "freshwater-fish",
    price: 99,
    originalPrice: 149,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    ],
    description: "Colorful and lively Fancy Guppies, perfect for beginners. Males display stunning tail patterns and vibrant colors. Easy to breed and care for.",
    careGuide: "Temperature: 72-82°F, pH: 6.8-7.8. Peaceful community fish. Best kept in groups with more females than males.",
    specifications: {
      "Size": "1.5-2 inches",
      "Lifespan": "2-3 years",
      "Tank Size": "10+ gallons",
      "Temperament": "Peaceful",
    },
    variants: [
      { name: "Variety", options: ["Moscow", "Cobra", "Koi", "Endler"] },
    ],
    inStock: true,
    isFeatured: true,
    rating: 4.7,
    reviews: 523,
    tags: ["fish", "guppy", "freshwater", "beginner", "colorful", "best-seller"],
  },
  {
    id: "fish-molly-1",
    name: "Molly Fish",
    slug: "molly-fish",
    category: "birds-fish",
    subcategory: "freshwater-fish",
    price: 149,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    ],
    description: "Hardy and adaptable Molly fish available in various colors. Great community fish that can tolerate slightly brackish water. Livebearers that breed easily.",
    careGuide: "Temperature: 72-82°F, pH: 7.5-8.5. Peaceful, can be kept in freshwater or brackish conditions.",
    specifications: {
      "Size": "3-4 inches",
      "Lifespan": "3-5 years",
      "Tank Size": "20+ gallons",
      "Temperament": "Peaceful",
    },
    variants: [
      { name: "Variety", options: ["Black", "Balloon", "Sailfin", "Gold Dust"] },
    ],
    inStock: true,
    rating: 4.5,
    reviews: 287,
    tags: ["fish", "molly", "freshwater", "livebearer"],
  },
  {
    id: "fish-platy-1",
    name: "Platy Fish",
    slug: "platy-fish",
    category: "birds-fish",
    subcategory: "freshwater-fish",
    price: 79,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    ],
    description: "Cheerful and colorful Platy fish, excellent for beginners. Hardy livebearers that come in a rainbow of colors and patterns.",
    careGuide: "Temperature: 70-82°F, pH: 7.0-8.2. Very peaceful, great community fish.",
    specifications: {
      "Size": "2-3 inches",
      "Lifespan": "3-5 years",
      "Tank Size": "10+ gallons",
      "Temperament": "Peaceful",
    },
    variants: [
      { name: "Variety", options: ["Red Wag", "Mickey Mouse", "Sunburst"] },
    ],
    inStock: true,
    rating: 4.6,
    reviews: 198,
    tags: ["fish", "platy", "freshwater", "beginner", "colorful"],
  },
  {
    id: "fish-swordtail-1",
    name: "Swordtail Fish",
    slug: "swordtail-fish",
    category: "birds-fish",
    subcategory: "freshwater-fish",
    price: 129,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    ],
    description: "Elegant Swordtail fish with distinctive elongated tail fin on males. Active swimmers that add movement and color to community tanks.",
    careGuide: "Temperature: 72-82°F, pH: 7.0-8.3. Active swimmers, need space to swim.",
    specifications: {
      "Size": "4-5 inches",
      "Lifespan": "3-5 years",
      "Tank Size": "20+ gallons",
      "Temperament": "Peaceful to Semi-aggressive",
    },
    variants: [
      { name: "Variety", options: ["Red", "Koi", "Pineapple"] },
    ],
    inStock: true,
    rating: 4.5,
    reviews: 156,
    tags: ["fish", "swordtail", "freshwater", "livebearer"],
  },
  {
    id: "fish-tetra-1",
    name: "Neon Tetra / Cardinal Tetra",
    slug: "neon-cardinal-tetra",
    category: "birds-fish",
    subcategory: "freshwater-fish",
    price: 49,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    ],
    description: "Stunning schooling fish with iridescent blue and red stripes. Cardinal Tetras have deeper red coloration. Best kept in groups of 6 or more.",
    careGuide: "Temperature: 73-81°F, pH: 5.5-7.0. Peaceful schooling fish, keep in groups.",
    specifications: {
      "Size": "1-2 inches",
      "Lifespan": "5-8 years",
      "Tank Size": "10+ gallons",
      "Temperament": "Peaceful",
    },
    variants: [
      { name: "Type", options: ["Neon Tetra", "Cardinal Tetra"] },
    ],
    inStock: true,
    rating: 4.8,
    reviews: 445,
    tags: ["fish", "tetra", "neon", "cardinal", "schooling", "freshwater"],
  },
  {
    id: "fish-goldfish-1",
    name: "Goldfish",
    slug: "fancy-goldfish",
    category: "birds-fish",
    subcategory: "freshwater-fish",
    price: 299,
    originalPrice: 399,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    ],
    description: "Classic and beloved Goldfish in various fancy varieties. Cold water fish that don't require heaters. Can live for decades with proper care.",
    careGuide: "Temperature: 65-75°F, pH: 7.0-8.0. Cold water fish, 20+ gallons per fish. Heavy feeders requiring good filtration.",
    specifications: {
      "Size": "6-8 inches (fancy varieties)",
      "Lifespan": "10-15+ years",
      "Tank Size": "20+ gallons per fish",
      "Temperament": "Peaceful",
    },
    variants: [
      { name: "Variety", options: ["Fantail", "Oranda", "Ryukin", "Black Moor", "Ranchu", "Lionhead"] },
    ],
    inStock: true,
    isFeatured: true,
    rating: 4.7,
    reviews: 378,
    tags: ["fish", "goldfish", "freshwater", "cold-water", "beginner", "best-seller"],
  },
  {
    id: "fish-betta-1",
    name: "Betta Fish",
    slug: "betta-siamese-fighting-fish",
    category: "birds-fish",
    subcategory: "freshwater-fish",
    price: 499,
    originalPrice: 699,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    ],
    description: "Magnificent Betta fish with flowing fins and vibrant colors. Known as Siamese Fighting Fish. Males must be kept separately. Wide variety of tail types available.",
    careGuide: "Temperature: 76-82°F, pH: 6.5-7.5. Keep males separate. Minimum 5 gallon tank recommended.",
    specifications: {
      "Size": "2.5-3 inches",
      "Lifespan": "3-5 years",
      "Tank Size": "5+ gallons",
      "Temperament": "Aggressive (males)",
    },
    variants: [
      { name: "Tail Type", options: ["Halfmoon", "Crowntail", "Plakat", "Dumbo", "Dragon Scale", "Koi"] },
    ],
    inStock: true,
    isFeatured: true,
    rating: 4.9,
    reviews: 612,
    tags: ["fish", "betta", "siamese", "fighting", "freshwater", "best-seller"],
  },
  {
    id: "fish-angelfish-1",
    name: "Angelfish",
    slug: "freshwater-angelfish",
    category: "birds-fish",
    subcategory: "freshwater-fish",
    price: 399,
    images: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    ],
    description: "Graceful freshwater Angelfish with elegant triangular shape. Beautiful centerpiece fish for community tanks. Various color morphs available.",
    careGuide: "Temperature: 76-84°F, pH: 6.5-7.5. Semi-aggressive, may eat small fish. Tank: 30+ gallons.",
    specifications: {
      "Size": "6 inches (body), 8+ inches (tall)",
      "Lifespan": "10-12 years",
      "Tank Size": "30+ gallons",
      "Temperament": "Semi-aggressive",
    },
    variants: [
      { name: "Variety", options: ["Marble", "Koi", "Black", "Albino"] },
    ],
    inStock: true,
    rating: 4.7,
    reviews: 234,
    tags: ["fish", "angelfish", "freshwater", "cichlid"],
  },
  {
    id: "fish-discus-1",
    name: "Discus Fish",
    slug: "discus-fish",
    category: "birds-fish",
    subcategory: "freshwater-fish",
    price: 2999,
    originalPrice: 3999,
    images: [
      "https://images.unsplash.com/photo-1571752726703-5e7d1f6a986d?w=800",
    ],
    description: "The King of the Aquarium! Stunning Discus with disc-shaped bodies and brilliant colors. Requires experienced care but rewards with unmatched beauty.",
    careGuide: "Temperature: 82-86°F, pH: 6.0-7.0. Requires pristine water quality. Keep in groups. Tank: 55+ gallons.",
    specifications: {
      "Size": "6-8 inches",
      "Lifespan": "10-15 years",
      "Tank Size": "55+ gallons",
      "Temperament": "Peaceful but shy",
    },
    variants: [
      { name: "Variety", options: ["Pigeon Blood", "Blue Diamond", "Red Turquoise"] },
    ],
    inStock: true,
    isNew: true,
    isFeatured: true,
    rating: 4.9,
    reviews: 156,
    tags: ["fish", "discus", "freshwater", "premium", "cichlid", "new-arrival"],
  },
  {
    id: "fish-corydoras-1",
    name: "Corydoras Catfish",
    slug: "corydoras-catfish",
    category: "birds-fish",
    subcategory: "freshwater-fish",
    price: 199,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    ],
    description: "Adorable bottom-dwelling Corydoras catfish. Excellent tank cleaners that help keep substrate clean. Social fish that should be kept in groups of 6+.",
    careGuide: "Temperature: 72-79°F, pH: 6.0-8.0. Peaceful bottom dwellers. Keep on soft substrate.",
    specifications: {
      "Size": "2-3 inches",
      "Lifespan": "5-10 years",
      "Tank Size": "20+ gallons",
      "Temperament": "Peaceful",
    },
    variants: [
      { name: "Species", options: ["Panda", "Bronze", "Sterbai"] },
    ],
    inStock: true,
    rating: 4.6,
    reviews: 267,
    tags: ["fish", "corydoras", "catfish", "freshwater", "bottom-dweller"],
  },
  {
    id: "fish-pleco-1",
    name: "Bristlenose Pleco",
    slug: "bristlenose-pleco",
    category: "birds-fish",
    subcategory: "freshwater-fish",
    price: 349,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    ],
    description: "Hardy algae-eating Bristlenose Pleco, perfect for controlling algae. Males develop distinctive bristles on nose. Stays smaller than common plecos.",
    careGuide: "Temperature: 73-81°F, pH: 6.5-7.5. Needs driftwood for digestion. Nocturnal.",
    specifications: {
      "Size": "4-6 inches",
      "Lifespan": "10-15 years",
      "Tank Size": "20+ gallons",
      "Temperament": "Peaceful",
    },
    variants: [
      { name: "Variety", options: ["Regular", "Albino", "Super Red", "Longfin"] },
    ],
    inStock: true,
    rating: 4.7,
    reviews: 198,
    tags: ["fish", "pleco", "bristlenose", "freshwater", "algae-eater"],
  },
  {
    id: "fish-danio-1",
    name: "GloFish Danio / Zebra Danio",
    slug: "glofish-zebra-danio",
    category: "birds-fish",
    subcategory: "freshwater-fish",
    price: 149,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    ],
    description: "Active and hardy Danios, perfect for beginners. GloFish varieties glow under blue light! Zebra Danios have classic horizontal stripes.",
    careGuide: "Temperature: 64-77°F, pH: 6.5-7.5. Very active, need swimming space. Keep in groups.",
    specifications: {
      "Size": "2 inches",
      "Lifespan": "3-5 years",
      "Tank Size": "10+ gallons",
      "Temperament": "Peaceful, Active",
    },
    variants: [
      { name: "Type", options: ["Zebra Danio", "GloFish (Various Colors)"] },
    ],
    inStock: true,
    rating: 4.5,
    reviews: 234,
    tags: ["fish", "danio", "glofish", "zebra", "freshwater", "beginner"],
  },
  {
    id: "fish-barb-1",
    name: "Tiger Barb / Cherry Barb",
    slug: "tiger-cherry-barb",
    category: "birds-fish",
    subcategory: "freshwater-fish",
    price: 79,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    ],
    description: "Active and colorful Barb fish. Tiger Barbs have striking black stripes while Cherry Barbs display beautiful red coloration. Keep in groups to reduce fin nipping.",
    careGuide: "Temperature: 74-82°F, pH: 6.0-7.0. Keep in groups of 6+ to minimize aggression.",
    specifications: {
      "Size": "2-3 inches",
      "Lifespan": "5-7 years",
      "Tank Size": "20+ gallons",
      "Temperament": "Semi-aggressive",
    },
    variants: [
      { name: "Type", options: ["Tiger Barb", "Cherry Barb"] },
    ],
    inStock: true,
    rating: 4.4,
    reviews: 167,
    tags: ["fish", "barb", "tiger", "cherry", "freshwater"],
  },
  {
    id: "fish-gourami-1",
    name: "Dwarf Gourami",
    slug: "dwarf-gourami",
    category: "birds-fish",
    subcategory: "freshwater-fish",
    price: 299,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    ],
    description: "Beautiful Dwarf Gourami with vibrant colors and peaceful temperament. Labyrinth fish that can breathe air. Males more colorful than females.",
    careGuide: "Temperature: 77-82°F, pH: 6.0-7.5. Peaceful, needs hiding spots and surface access.",
    specifications: {
      "Size": "2-3 inches",
      "Lifespan": "4-6 years",
      "Tank Size": "10+ gallons",
      "Temperament": "Peaceful",
    },
    variants: [
      { name: "Variety", options: ["Powder Blue", "Flame"] },
    ],
    inStock: true,
    rating: 4.6,
    reviews: 189,
    tags: ["fish", "gourami", "dwarf", "freshwater", "labyrinth"],
  },

  // ═══════════════════ MARINE FISH ═══════════════════
  {
    id: "fish-clownfish-1",
    name: "Ocellaris Clownfish",
    slug: "ocellaris-clownfish",
    category: "birds-fish",
    subcategory: "marine-fish",
    price: 999,
    originalPrice: 1299,
    images: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    ],
    description: "The famous 'Nemo' fish! Hardy and beautiful Ocellaris Clownfish perfect for beginner marine aquarists. Can be paired with anemones for a stunning display.",
    careGuide: "Temperature: 75-82°F, Salinity: 1.020-1.025. Hardy marine fish. Can host in anemones but not required.",
    specifications: {
      "Size": "3-4 inches",
      "Lifespan": "10-15 years",
      "Tank Size": "20+ gallons",
      "Temperament": "Semi-aggressive",
    },
    variants: [
      { name: "Variety", options: ["Normal", "Picasso", "Snowflake", "Black Ice"] },
    ],
    inStock: true,
    isFeatured: true,
    rating: 4.9,
    reviews: 345,
    tags: ["fish", "clownfish", "marine", "saltwater", "nemo", "best-seller"],
  },
  {
    id: "fish-royal-gramma-1",
    name: "Royal Gramma",
    slug: "royal-gramma",
    category: "birds-fish",
    subcategory: "marine-fish",
    price: 1499,
    images: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    ],
    description: "Stunning Royal Gramma with vibrant purple and yellow coloration. Hardy and reef-safe. Often hides in caves and overhangs.",
    careGuide: "Temperature: 72-78°F, Salinity: 1.020-1.025. Needs hiding spots. Peaceful but territorial.",
    specifications: {
      "Size": "3 inches",
      "Lifespan": "5-6 years",
      "Tank Size": "30+ gallons",
      "Temperament": "Semi-aggressive",
    },
    inStock: true,
    rating: 4.7,
    reviews: 123,
    tags: ["fish", "royal-gramma", "marine", "saltwater", "reef-safe"],
  },
  {
    id: "fish-cardinal-1",
    name: "Banggai Cardinalfish",
    slug: "banggai-cardinalfish",
    category: "birds-fish",
    subcategory: "marine-fish",
    price: 1299,
    images: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    ],
    description: "Elegant Banggai Cardinalfish with distinctive black stripes and long fins. Peaceful and reef-safe. Often hovers near urchins or branching corals.",
    careGuide: "Temperature: 75-82°F, Salinity: 1.020-1.025. Peaceful, can be kept in pairs or small groups.",
    specifications: {
      "Size": "3 inches",
      "Lifespan": "5+ years",
      "Tank Size": "30+ gallons",
      "Temperament": "Peaceful",
    },
    inStock: true,
    rating: 4.6,
    reviews: 89,
    tags: ["fish", "cardinalfish", "banggai", "marine", "saltwater"],
  },
  {
    id: "fish-tang-1",
    name: "Yellow Tang / Blue Tang",
    slug: "yellow-blue-tang",
    category: "birds-fish",
    subcategory: "marine-fish",
    price: 3999,
    originalPrice: 4999,
    images: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    ],
    description: "Iconic Tang fish - Yellow Tang is bright sunshine yellow, Blue Tang (Dory) has striking blue coloration. Active swimmers that need large tanks.",
    careGuide: "Temperature: 75-82°F, Salinity: 1.020-1.025. Need large tanks with swimming room. Herbivores - provide algae.",
    specifications: {
      "Size": "8-10 inches",
      "Lifespan": "10-20 years",
      "Tank Size": "100+ gallons",
      "Temperament": "Semi-aggressive",
    },
    variants: [
      { name: "Species", options: ["Yellow Tang", "Blue Tang"] },
    ],
    inStock: true,
    rating: 4.8,
    reviews: 156,
    tags: ["fish", "tang", "yellow", "blue", "dory", "marine", "saltwater"],
  },
  {
    id: "fish-chromis-1",
    name: "Green Chromis",
    slug: "green-chromis",
    category: "birds-fish",
    subcategory: "marine-fish",
    price: 399,
    images: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    ],
    description: "Peaceful and active Green Chromis, perfect for schooling in reef tanks. Hardy and reef-safe. Best kept in groups of 5+.",
    careGuide: "Temperature: 75-82°F, Salinity: 1.020-1.025. Very peaceful, excellent community fish.",
    specifications: {
      "Size": "3-4 inches",
      "Lifespan": "8-15 years",
      "Tank Size": "30+ gallons",
      "Temperament": "Peaceful",
    },
    inStock: true,
    rating: 4.5,
    reviews: 178,
    tags: ["fish", "chromis", "green", "marine", "saltwater", "schooling"],
  },

  // ═══════════════════ FISH ACCESSORIES ═══════════════════
  {
    id: "acc-tank-1",
    name: "Aquarium Tanks",
    slug: "aquarium-tanks",
    category: "birds-fish",
    subcategory: "fish-accessories",
    price: 1999,
    images: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    ],
    description: "High-quality glass aquarium tanks in various sizes. Crystal clear glass with polished edges. Suitable for freshwater and saltwater setups.",
    specifications: {
      "Material": "Float Glass",
      "Thickness": "6-12mm",
      "Warranty": "1 Year",
    },
    variants: [
      { name: "Size", options: ["10L", "20L", "30L", "50L", "100L", "Rimless", "Planted"] },
    ],
    inStock: true,
    rating: 4.7,
    reviews: 234,
    tags: ["accessory", "tank", "aquarium", "glass"],
  },
  {
    id: "acc-filter-1",
    name: "Hang-on-Back Filter",
    slug: "hang-on-back-filter",
    category: "birds-fish",
    subcategory: "fish-accessories",
    price: 799,
    images: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    ],
    description: "Easy-to-install HOB filter for aquariums. Multi-stage filtration with adjustable flow. Quiet operation.",
    specifications: {
      "Filtration": "3-Stage",
      "Power": "5-15W",
    },
    variants: [
      { name: "Flow Rate", options: ["100 LPH", "200 LPH", "400 LPH", "800 LPH"] },
    ],
    inStock: true,
    rating: 4.6,
    reviews: 312,
    tags: ["accessory", "filter", "hob", "filtration"],
  },
  {
    id: "acc-heater-1",
    name: "Submersible Heater",
    slug: "submersible-aquarium-heater",
    category: "birds-fish",
    subcategory: "fish-accessories",
    price: 599,
    images: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    ],
    description: "Fully submersible aquarium heater with precise temperature control. Auto shut-off for safety. Suitable for freshwater and saltwater.",
    specifications: {
      "Material": "Quartz Glass",
      "Accuracy": "±0.5°C",
    },
    variants: [
      { name: "Wattage", options: ["50W", "100W", "200W", "300W"] },
    ],
    inStock: true,
    rating: 4.7,
    reviews: 256,
    tags: ["accessory", "heater", "temperature"],
  },
  {
    id: "acc-led-1",
    name: "LED Aquarium Light",
    slug: "led-aquarium-light",
    category: "birds-fish",
    subcategory: "fish-accessories",
    price: 1499,
    images: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    ],
    description: "Full spectrum LED light for aquariums. Programmable sunrise/sunset simulation. Promotes plant growth and enhances fish colors.",
    specifications: {
      "LED Type": "SMD",
      "Lifespan": "50,000 hours",
    },
    variants: [
      { name: "Type", options: ["RGB", "WRGB", "Marine Blue"] },
    ],
    inStock: true,
    rating: 4.8,
    reviews: 189,
    tags: ["accessory", "light", "led", "planted"],
  },
  {
    id: "acc-airpump-1",
    name: "Air Pump + Air Stone",
    slug: "air-pump-air-stone",
    category: "birds-fish",
    subcategory: "fish-accessories",
    price: 399,
    images: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    ],
    description: "Quiet air pump with air stone for aquarium oxygenation. Essential for fish health. Includes airline tubing and check valve.",
    inStock: true,
    rating: 4.5,
    reviews: 345,
    tags: ["accessory", "air-pump", "oxygenation"],
  },
  {
    id: "acc-substrate-1",
    name: "Aquarium Substrate",
    slug: "aquarium-substrate",
    category: "birds-fish",
    subcategory: "fish-accessories",
    price: 499,
    images: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    ],
    description: "Premium aquarium substrate for healthy tank setup. Various options for different aquascape styles. Pre-washed and ready to use.",
    specifications: {
      "Weight": "5kg bag",
    },
    variants: [
      { name: "Type", options: ["Black Gravel", "White Sand", "ADA Soil"] },
    ],
    inStock: true,
    rating: 4.6,
    reviews: 178,
    tags: ["accessory", "substrate", "gravel", "sand"],
  },
  {
    id: "acc-driftwood-1",
    name: "Driftwood & Rocks",
    slug: "driftwood-rocks",
    category: "birds-fish",
    subcategory: "fish-accessories",
    price: 699,
    images: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    ],
    description: "Natural driftwood and aquascaping rocks for stunning tank decoration. Pre-cleaned and aquarium-safe. Creates natural hiding spots for fish.",
    variants: [
      { name: "Size", options: ["Small", "Medium", "Large"] },
    ],
    inStock: true,
    rating: 4.7,
    reviews: 145,
    tags: ["accessory", "driftwood", "rocks", "decoration"],
  },
  {
    id: "acc-conditioner-1",
    name: "Water Conditioner & Beneficial Bacteria",
    slug: "water-conditioner-bacteria",
    category: "birds-fish",
    subcategory: "fish-accessories",
    price: 349,
    images: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    ],
    description: "Essential water treatment for healthy aquariums. Removes chlorine/chloramine and adds beneficial bacteria for cycling.",
    inStock: true,
    rating: 4.8,
    reviews: 423,
    tags: ["accessory", "water-conditioner", "bacteria", "cycling"],
  },
  {
    id: "acc-food-1",
    name: "Fish Food",
    slug: "premium-fish-food",
    category: "birds-fish",
    subcategory: "fish-accessories",
    price: 199,
    images: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    ],
    description: "High-quality fish food for optimal health and color. Various formulations for different fish types. No cloudiness guaranteed.",
    variants: [
      { name: "Type", options: ["Flakes", "Pellets", "Frozen Bloodworm"] },
    ],
    inStock: true,
    rating: 4.6,
    reviews: 567,
    tags: ["accessory", "food", "nutrition"],
  },
  {
    id: "acc-tools-1",
    name: "Fish Net & Algae Scraper",
    slug: "fish-net-algae-scraper",
    category: "birds-fish",
    subcategory: "fish-accessories",
    price: 199,
    images: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    ],
    description: "Essential aquarium maintenance tools. Soft mesh fish net for safe handling. Algae scraper with replaceable blade.",
    inStock: true,
    rating: 4.4,
    reviews: 234,
    tags: ["accessory", "net", "algae-scraper", "maintenance"],
  },
  {
    id: "acc-co2-1",
    name: "CO2 System Set",
    slug: "co2-system-planted-tank",
    category: "birds-fish",
    subcategory: "fish-accessories",
    price: 3999,
    originalPrice: 4999,
    images: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    ],
    description: "Complete CO2 injection system for planted tanks. Includes regulator, solenoid, diffuser, and bubble counter. Essential for lush plant growth.",
    inStock: true,
    isNew: true,
    rating: 4.8,
    reviews: 89,
    tags: ["accessory", "co2", "planted-tank", "aquascape"],
  },
  {
    id: "acc-testkit-1",
    name: "Test Kits",
    slug: "water-test-kits",
    category: "birds-fish",
    subcategory: "fish-accessories",
    price: 599,
    images: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    ],
    description: "Accurate water testing kits for monitoring aquarium parameters. Essential for fish health and water quality management.",
    variants: [
      { name: "Type", options: ["pH", "Ammonia", "Nitrite", "Nitrate", "Master Kit"] },
    ],
    inStock: true,
    rating: 4.7,
    reviews: 312,
    tags: ["accessory", "test-kit", "water-quality"],
  },
  {
    id: "acc-skimmer-1",
    name: "Protein Skimmer",
    slug: "protein-skimmer-marine",
    category: "birds-fish",
    subcategory: "fish-accessories",
    price: 2999,
    images: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    ],
    description: "Essential protein skimmer for marine/saltwater aquariums. Removes organic waste before it breaks down. Available in nano and medium sizes.",
    variants: [
      { name: "Size", options: ["Nano (up to 50L)", "Medium (up to 200L)"] },
    ],
    inStock: true,
    rating: 4.6,
    reviews: 78,
    tags: ["accessory", "skimmer", "marine", "saltwater"],
  },
];

