import { Product } from "./store";

export const categories = [
  {
    id: "aquarium-fish",
    name: "Aquarium Fish",
    slug: "aquarium-fish",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    description: "Premium cloned & exotic aquarium fish",
    featured: true,
    subcategories: [
      { name: "Cloned Fish", slug: "cloned-fish" },
      { name: "Tropical Fish", slug: "tropical-fish" },
      { name: "Goldfish", slug: "goldfish" },
      { name: "Betta Fish", slug: "betta-fish" },
      { name: "Koi Fish", slug: "koi-fish" },
      { name: "Cichlids", slug: "cichlids" },
      { name: "Guppies", slug: "guppies" },
      { name: "Discus", slug: "discus" },
      { name: "Arowana", slug: "arowana" },
      { name: "Flowerhorn", slug: "flowerhorn" },
    ],
  },
  {
    id: "accessories",
    name: "Accessories",
    slug: "accessories",
    image: "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    description: "Premium aquarium accessories & supplies",
    subcategories: [
      { name: "Aquarium Tanks", slug: "aquarium-tanks" },
      { name: "Filters", slug: "filters" },
      { name: "Heaters", slug: "heaters" },
      { name: "Decorations", slug: "decorations" },
      { name: "Lighting", slug: "lighting" },
      { name: "Food & Nutrition", slug: "food-nutrition" },
      { name: "Air Pumps", slug: "air-pumps" },
      { name: "Substrate & Gravel", slug: "substrate-gravel" },
      { name: "Plants", slug: "plants" },
      { name: "Water Treatment", slug: "water-treatment" },
    ],
  },
];

export const products: Product[] = [
  // Cloned Fish
  {
    id: "cloned-arowana-1",
    name: "Premium Cloned Asian Arowana",
    slug: "premium-cloned-asian-arowana",
    category: "aquarium-fish",
    subcategory: "cloned-fish",
    price: 125000,
    originalPrice: 150000,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    ],
    description: "Our flagship cloned Asian Arowana features identical genetics to championship-winning specimens. This magnificent fish showcases vibrant red and gold coloration with perfect scale formation.",
    careGuide: "Temperature: 75-82°F, pH: 6.5-7.5, Tank Size: 250+ gallons. Feed high-quality pellets, live/frozen foods. Requires excellent filtration and weekly water changes.",
    specifications: {
      "Size": "12-18 inches",
      "Lifespan": "15-20 years",
      "Diet": "Carnivore",
      "Temperament": "Semi-aggressive",
      "Tank Size": "250+ gallons",
    },
    variants: [
      { name: "Color", options: ["Super Red", "Golden Crossback", "Platinum"] },
      { name: "Size", options: ["6 inch", "12 inch", "18 inch"] },
    ],
    inStock: true,
    isNew: true,
    isFeatured: true,
    rating: 4.9,
    reviews: 127,
    tags: ["cloned", "premium", "arowana", "rare"],
  },
  {
    id: "cloned-discus-1",
    name: "Cloned Blue Diamond Discus",
    slug: "cloned-blue-diamond-discus",
    category: "aquarium-fish",
    subcategory: "cloned-fish",
    price: 8500,
    originalPrice: 10000,
    images: [
      "https://images.unsplash.com/photo-1571752726703-5e7d1f6a986d?w=800",
    ],
    description: "Stunning cloned Blue Diamond Discus with perfect circular body shape and brilliant cobalt blue coloration. Genetically identical to award-winning specimens.",
    careGuide: "Temperature: 82-86°F, pH: 6.0-7.0, Tank Size: 55+ gallons. Requires pristine water quality and varied diet including beef heart and bloodworms.",
    inStock: true,
    isNew: true,
    isFeatured: true,
    rating: 4.8,
    reviews: 89,
    tags: ["cloned", "discus", "blue"],
  },
  {
    id: "cloned-flowerhorn-1",
    name: "Cloned Super Red Dragon Flowerhorn",
    slug: "cloned-super-red-dragon-flowerhorn",
    category: "aquarium-fish",
    subcategory: "cloned-fish",
    price: 35000,
    originalPrice: 42000,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    ],
    description: "Premium cloned Flowerhorn with massive kok (head protrusion) and vivid red coloration. Perfect genetics ensure impressive growth and coloration.",
    careGuide: "Temperature: 80-86°F, pH: 7.0-8.0, Tank Size: 75+ gallons. Aggressive fish, keep alone. Feed high-quality pellets and occasional treats.",
    inStock: true,
    isFeatured: true,
    rating: 4.7,
    reviews: 156,
    tags: ["cloned", "flowerhorn", "red"],
  },
  {
    id: "cloned-platinum-arowana",
    name: "Cloned Platinum Arowana",
    slug: "cloned-platinum-arowana",
    category: "aquarium-fish",
    subcategory: "cloned-fish",
    price: 250000,
    originalPrice: 300000,
    images: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    ],
    description: "Extremely rare cloned Platinum Arowana with pure white scales and metallic sheen. One of the most prestigious fish in the hobby.",
    careGuide: "Temperature: 75-82°F, pH: 6.5-7.5, Tank Size: 300+ gallons. Requires expert care and pristine water conditions.",
    inStock: true,
    isNew: true,
    isFeatured: true,
    rating: 5.0,
    reviews: 45,
    tags: ["cloned", "platinum", "arowana", "ultra-rare"],
  },
  // Tropical Fish
  {
    id: "neon-tetra-school",
    name: "Neon Tetra School (10 Fish)",
    slug: "neon-tetra-school",
    category: "aquarium-fish",
    subcategory: "tropical-fish",
    price: 599,
    originalPrice: 799,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    ],
    description: "A beautiful school of 10 vibrant Neon Tetras. Their iridescent blue and red stripes create a stunning display in any planted aquarium.",
    careGuide: "Temperature: 70-81°F, pH: 6.0-7.0. Peaceful community fish. Keep in groups of 6+.",
    inStock: true,
    rating: 4.6,
    reviews: 324,
    tags: ["tetra", "schooling", "beginner"],
  },
  {
    id: "angelfish-marble",
    name: "Marble Angelfish Pair",
    slug: "marble-angelfish-pair",
    category: "aquarium-fish",
    subcategory: "tropical-fish",
    price: 1499,
    images: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    ],
    description: "Elegant pair of Marble Angelfish with beautiful black and white marbling patterns. Perfect centerpiece fish for community aquariums.",
    careGuide: "Temperature: 76-84°F, pH: 6.5-7.5, Tank Size: 30+ gallons. Semi-aggressive, may eat small fish.",
    inStock: true,
    rating: 4.5,
    reviews: 178,
    tags: ["angelfish", "pair", "community"],
  },
  {
    id: "cardinal-tetra-school",
    name: "Cardinal Tetra School (15 Fish)",
    slug: "cardinal-tetra-school",
    category: "aquarium-fish",
    subcategory: "tropical-fish",
    price: 899,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    ],
    description: "Stunning school of Cardinal Tetras with deeper red coloration than Neons. Perfect for planted Amazon-style aquariums.",
    careGuide: "Temperature: 73-81°F, pH: 5.5-7.0. Peaceful schooling fish.",
    inStock: true,
    isNew: true,
    rating: 4.7,
    reviews: 215,
    tags: ["tetra", "cardinal", "schooling"],
  },
  // Betta Fish
  {
    id: "betta-galaxy-koi",
    name: "Galaxy Koi Betta Male",
    slug: "galaxy-koi-betta-male",
    category: "aquarium-fish",
    subcategory: "betta-fish",
    price: 2999,
    originalPrice: 3500,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    ],
    description: "Stunning Galaxy Koi pattern Betta with speckled coloration resembling a starry night sky. Premium quality imported from Thailand.",
    careGuide: "Temperature: 76-82°F, pH: 6.5-7.5, Tank Size: 5+ gallons. Keep males separate. Varied diet recommended.",
    inStock: true,
    isNew: true,
    rating: 4.9,
    reviews: 412,
    tags: ["betta", "galaxy", "koi", "premium"],
  },
  {
    id: "betta-halfmoon",
    name: "Halfmoon Betta - Dragon Scale",
    slug: "halfmoon-betta-dragon-scale",
    category: "aquarium-fish",
    subcategory: "betta-fish",
    price: 1999,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    ],
    description: "Magnificent Halfmoon Betta with dragon scale pattern. Features a 180-degree tail spread and metallic scaling.",
    inStock: true,
    rating: 4.7,
    reviews: 289,
    tags: ["betta", "halfmoon", "dragon"],
  },
  {
    id: "betta-dumbo-ear",
    name: "Dumbo Ear Betta - Multicolor",
    slug: "dumbo-ear-betta-multicolor",
    category: "aquarium-fish",
    subcategory: "betta-fish",
    price: 2499,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    ],
    description: "Beautiful Dumbo Ear Betta with oversized pectoral fins that resemble elephant ears. Multicolor variety.",
    inStock: true,
    isFeatured: true,
    rating: 4.8,
    reviews: 167,
    tags: ["betta", "dumbo", "elephant ear"],
  },
  // Goldfish
  {
    id: "ranchu-goldfish",
    name: "Japanese Ranchu Goldfish",
    slug: "japanese-ranchu-goldfish",
    category: "aquarium-fish",
    subcategory: "goldfish",
    price: 4500,
    originalPrice: 5500,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    ],
    description: "Premium Japanese Ranchu Goldfish known as the 'King of Goldfish'. Features a distinctive head growth and egg-shaped body.",
    careGuide: "Temperature: 65-75°F, pH: 7.0-8.0, Tank Size: 20+ gallons per fish. Cold water fish, no heater needed.",
    inStock: true,
    isFeatured: true,
    rating: 4.8,
    reviews: 156,
    tags: ["goldfish", "ranchu", "japanese", "premium"],
  },
  {
    id: "oranda-goldfish",
    name: "Red Cap Oranda Goldfish",
    slug: "red-cap-oranda-goldfish",
    category: "aquarium-fish",
    subcategory: "goldfish",
    price: 2999,
    images: [
      "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    ],
    description: "Beautiful Red Cap Oranda with white body and vibrant red hood growth. A classic and beloved variety.",
    inStock: true,
    rating: 4.6,
    reviews: 234,
    tags: ["goldfish", "oranda", "red cap"],
  },
  // Koi Fish
  {
    id: "kohaku-koi",
    name: "Premium Kohaku Koi",
    slug: "premium-kohaku-koi",
    category: "aquarium-fish",
    subcategory: "koi-fish",
    price: 15000,
    originalPrice: 18000,
    images: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    ],
    description: "High-quality Kohaku Koi with crisp white skin and vibrant red (hi) pattern. Japanese bloodline.",
    careGuide: "Temperature: 59-77°F, pH: 7.0-8.5. Requires pond or very large tank (500+ gallons).",
    inStock: true,
    isFeatured: true,
    rating: 4.9,
    reviews: 78,
    tags: ["koi", "kohaku", "japanese", "pond"],
  },
  // Accessories
  {
    id: "aquarium-filter-canister",
    name: "Premium Canister Filter 1000L/H",
    slug: "premium-canister-filter",
    category: "accessories",
    subcategory: "filters",
    price: 8999,
    originalPrice: 11999,
    images: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    ],
    description: "High-performance canister filter suitable for aquariums up to 300 gallons. Ultra-quiet operation with multi-stage filtration.",
    specifications: {
      "Flow Rate": "1000 L/H",
      "Tank Size": "Up to 300 gallons",
      "Stages": "4-stage filtration",
      "Power": "35W",
    },
    inStock: true,
    isFeatured: true,
    rating: 4.7,
    reviews: 456,
    tags: ["filter", "canister", "premium"],
  },
  {
    id: "led-aquarium-light",
    name: "RGB LED Aquarium Light Bar",
    slug: "rgb-led-aquarium-light",
    category: "accessories",
    subcategory: "lighting",
    price: 3499,
    images: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    ],
    description: "Full spectrum RGB LED light with remote control. Simulates sunrise/sunset. Perfect for planted tanks.",
    inStock: true,
    rating: 4.6,
    reviews: 312,
    tags: ["led", "light", "rgb", "planted"],
  },
  {
    id: "aquarium-heater",
    name: "Titanium Aquarium Heater 300W",
    slug: "titanium-aquarium-heater",
    category: "accessories",
    subcategory: "heaters",
    price: 2499,
    images: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    ],
    description: "Titanium heating element for durability. Digital temperature control with LED display. Suitable for saltwater and freshwater.",
    inStock: true,
    rating: 4.8,
    reviews: 278,
    tags: ["heater", "titanium", "digital"],
  },
  {
    id: "air-pump-silent",
    name: "Ultra Silent Air Pump",
    slug: "ultra-silent-air-pump",
    category: "accessories",
    subcategory: "air-pumps",
    price: 1299,
    images: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    ],
    description: "Whisper-quiet air pump with adjustable flow. Perfect for bedrooms and offices. Includes airline tubing.",
    inStock: true,
    isNew: true,
    rating: 4.5,
    reviews: 189,
    tags: ["air pump", "silent", "oxygenation"],
  },
  {
    id: "aquarium-decorations-set",
    name: "Natural Driftwood & Rock Set",
    slug: "natural-driftwood-rock-set",
    category: "accessories",
    subcategory: "decorations",
    price: 1999,
    originalPrice: 2499,
    images: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    ],
    description: "Premium natural driftwood and dragon stone set. Pre-cleaned and ready for aquarium use. Creates stunning aquascapes.",
    inStock: true,
    isFeatured: true,
    rating: 4.7,
    reviews: 145,
    tags: ["driftwood", "rocks", "aquascape", "natural"],
  },
  {
    id: "fish-food-premium",
    name: "Premium Color Enhancing Pellets",
    slug: "premium-color-enhancing-pellets",
    category: "accessories",
    subcategory: "food-nutrition",
    price: 799,
    images: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    ],
    description: "High-quality floating pellets with color-enhancing ingredients. Suitable for all tropical fish. No cloudiness guaranteed.",
    inStock: true,
    rating: 4.6,
    reviews: 567,
    tags: ["food", "pellets", "color", "nutrition"],
  },
  {
    id: "co2-system",
    name: "Complete CO2 System Kit",
    slug: "complete-co2-system-kit",
    category: "accessories",
    subcategory: "plants",
    price: 5999,
    originalPrice: 7499,
    images: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    ],
    description: "Professional CO2 injection system for planted tanks. Includes regulator, solenoid, diffuser, and bubble counter.",
    inStock: true,
    isNew: true,
    isFeatured: true,
    rating: 4.8,
    reviews: 98,
    tags: ["co2", "planted tank", "aquascape"],
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Rajesh Sharma",
    location: "Tirunelveli",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
    rating: 5,
    text: "Amazing quality cloned Arowana! The fish arrived healthy and is thriving in my tank. Rainbow Aqua and Pets's live arrival guarantee gave me confidence to order.",
    product: "Cloned Asian Arowana",
  },
  {
    id: 2,
    name: "Priya Patel",
    location: "Ahmedabad",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
    rating: 5,
    text: "Best place to buy aquarium fish online! The packaging was excellent and customer service is top-notch. My Discus fish are beautiful!",
    product: "Blue Diamond Discus",
  },
  {
    id: 3,
    name: "Amit Kumar",
    location: "Delhi",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100",
    rating: 5,
    text: "I've ordered multiple times from Rainbow Aqua and Pets. The quality is consistent and prices are reasonable. Highly recommend for serious aquarists!",
    product: "Various Fish & Accessories",
  },
  {
    id: 4,
    name: "Sneha Reddy",
    location: "Hyderabad",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100",
    rating: 5,
    text: "The cloned Flowerhorn I received exceeded my expectations. Perfect kok development and coloration. Will definitely order again!",
    product: "Cloned Flowerhorn",
  },
  {
    id: 5,
    name: "Vikram Singh",
    location: "Bangalore",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100",
    rating: 4,
    text: "Great selection of Betta fish! The Galaxy Koi Betta I received is even more beautiful than the photos. Will definitely order again.",
    product: "Galaxy Koi Betta",
  },
];

export const blogPosts = [
  {
    id: 1,
    title: "The Science Behind Cloned Aquarium Fish",
    slug: "science-behind-cloned-aquarium-fish",
    excerpt: "Discover how cutting-edge cloning technology is revolutionizing the aquarium hobby, creating genetically perfect specimens.",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    author: "Dr. Arun Mehta",
    date: "2024-12-01",
    category: "Technology",
    readTime: "8 min read",
  },
  {
    id: 2,
    title: "Complete Care Guide for Discus Fish",
    slug: "complete-care-guide-discus-fish",
    excerpt: "Everything you need to know about keeping the 'King of the Aquarium' happy and healthy in your home.",
    image: "https://images.unsplash.com/photo-1571752726703-5e7d1f6a986d?w=800",
    author: "Meera Iyer",
    date: "2024-11-28",
    category: "Care Guides",
    readTime: "12 min read",
  },
  {
    id: 3,
    title: "Setting Up Your First Planted Aquarium",
    slug: "setting-up-first-planted-aquarium",
    excerpt: "A beginner's guide to creating a stunning underwater garden with live plants and fish.",
    image: "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800",
    author: "Rohit Kapoor",
    date: "2024-11-25",
    category: "Tutorials",
    readTime: "15 min read",
  },
  {
    id: 4,
    title: "Top 10 Beginner-Friendly Fish for New Hobbyists",
    slug: "top-10-beginner-friendly-fish",
    excerpt: "Start your fishkeeping journey with these hardy and beautiful species perfect for beginners.",
    image: "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=800",
    author: "Ananya Gupta",
    date: "2024-11-20",
    category: "Guides",
    readTime: "6 min read",
  },
];

export const faqs = [
  {
    question: "What is cloned fish and is it safe?",
    answer: "Cloned fish are genetically identical copies of exceptional specimens. The process is completely safe and produces healthy fish with guaranteed desirable traits like perfect coloration and body shape.",
  },
  {
    question: "Do you offer live arrival guarantee?",
    answer: "Yes! We offer a 100% live arrival guarantee on all fish orders. If any fish arrives DOA (Dead on Arrival), we'll replace it or refund you completely.",
  },
  {
    question: "How do you ship live fish?",
    answer: "We use specialized insulated boxes with oxygen-infused water, heat/cold packs as needed, and express overnight shipping to ensure your fish arrive healthy and stress-free.",
  },
  {
    question: "What payment methods do you accept?",
    answer: "We accept all major credit/debit cards, UPI payments, net banking, and Cash on Delivery (COD) for orders under ₹50,000.",
  },
  {
    question: "Can I visit your store in Tirunelveli?",
    answer: "Absolutely! You can visit Rainbow Aquarium & Pets in Palayamkottai, Tirunelveli to see products in person and get help from the team.",
  },
];
