import { Product, HeroSlide, Testimonial, BlogPost, Collection, FAQItem, Stat } from '@/types'

// Aquarium images from Unsplash
const aquariumImages = {
  fish: [
    'https://images.unsplash.com/photo-1520990059-1e21b5c78e93?w=800',
    'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=800',
    'https://images.unsplash.com/photo-1571752726703-5e7d1f6a986d?w=800',
    'https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=800',
    'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
  ],
  tanks: [
    'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=800',
    'https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=800',
    'https://images.unsplash.com/photo-1559717201-fbb671ff56b7?w=800',
  ],
  plants: [
    'https://images.unsplash.com/photo-1585241936939-be4099591252?w=800',
    'https://images.unsplash.com/photo-1596123068611-c89d922d2351?w=800',
  ],
  equipment: [
    'https://images.unsplash.com/photo-1584461049019-eb37661c7a7e?w=800',
    'https://images.unsplash.com/photo-1602491674275-316d95560fb1?w=800',
  ],
}

// Helper to generate reviews
const generateReviews = (count: number) => {
  const names = ['Rajesh K.', 'Priya M.', 'Arun S.', 'Kavitha R.', 'Suresh P.', 'Deepa G.', 'Karthik T.', 'Meena B.', 'Vijay V.', 'Lakshmi N.']
  const titles = ['Excellent quality!', 'My fish love it!', 'Great product', 'Highly recommend', 'Best purchase ever!', 'Worth every rupee!']
  const contents = [
    'This product exceeded my expectations. My aquarium looks amazing now!',
    'Great quality product. Fast delivery to Salem. Will buy again!',
    'Amazing quality at this price. My fish are so happy with this purchase.',
    'Best aquarium store in India! Highly recommended for all aquarists.',
    'Superb product, exactly as described. My planted tank is thriving!',
  ]
  const reviews = []
  for (let i = 0; i < count; i++) {
    reviews.push({
      id: `review-${i}`,
      author: names[i % names.length],
      rating: 4 + Math.random(),
      title: titles[i % titles.length],
      content: contents[i % contents.length],
      date: new Date(Date.now() - i * 86400000 * 3).toISOString(),
      verified: Math.random() > 0.3,
      helpful: Math.floor(Math.random() * 50),
    })
  }
  return reviews
}

// Products data - 50 aquarium products
export const products: Product[] = [
  // Live Fish (1-12)
  {
    id: '1',
    name: 'Premium Fancy Guppy Pair',
    slug: 'premium-fancy-guppy-pair',
    description: 'Beautiful imported fancy guppies with vibrant colors and elegant tails. Perfect for community tanks. These premium specimens showcase stunning red, blue, and yellow patterns.',
    shortDescription: 'Colorful fancy guppy breeding pair',
    price: 299,
    compareAtPrice: 399,
    category: 'Live Fish',
    subcategory: 'Guppies',
    tags: ['guppy', 'fancy', 'colorful', 'community-fish'],
    images: [aquariumImages.fish[0], aquariumImages.fish[1]],
    variants: [
      { id: 'v1-1', name: 'Red Mosaic Pair', price: 299, stock: 20 },
      { id: 'v1-2', name: 'Blue Diamond Pair', price: 349, stock: 15 },
      { id: 'v1-3', name: 'Yellow Cobra Pair', price: 279, stock: 25 },
    ],
    reviews: generateReviews(5),
    rating: 4.8,
    reviewCount: 245,
    stock: 60,
    sku: 'LF-001',
    brand: 'Cloning Aqua Pets',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: true,
    petType: 'fish',
    createdAt: '2024-01-15',
    specifications: { Size: '2-3 inches', 'Tank Size': '10+ gallons', Temperature: '72-82°F' },
  },
  {
    id: '2',
    name: 'Japanese Koi Fish - Kohaku',
    slug: 'japanese-koi-kohaku',
    description: 'Beautiful Kohaku variety Japanese Koi with pristine white base and vibrant red patterns. Ideal for outdoor ponds and large aquariums.',
    shortDescription: 'Premium Kohaku Japanese Koi',
    price: 2499,
    compareAtPrice: 2999,
    category: 'Live Fish',
    subcategory: 'Koi',
    tags: ['koi', 'japanese', 'kohaku', 'pond-fish'],
    images: [aquariumImages.fish[1], aquariumImages.fish[2]],
    variants: [
      { id: 'v2-1', name: '4-5 inches', price: 2499, stock: 8 },
      { id: 'v2-2', name: '6-8 inches', price: 4999, stock: 5 },
      { id: 'v2-3', name: '10-12 inches', price: 8999, stock: 3 },
    ],
    reviews: generateReviews(4),
    rating: 4.9,
    reviewCount: 89,
    stock: 16,
    sku: 'LF-002',
    brand: 'Cloning Aqua Pets',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: true,
    petType: 'fish',
    createdAt: '2024-02-01',
  },
  {
    id: '3',
    name: 'Discus Fish - Red Turquoise',
    slug: 'discus-red-turquoise',
    description: 'Stunning Red Turquoise Discus, the king of aquarium fish. Known for their vibrant colors and elegant disc-shaped body.',
    shortDescription: 'Premium Red Turquoise Discus',
    price: 1999,
    category: 'Live Fish',
    subcategory: 'Discus',
    tags: ['discus', 'tropical', 'premium', 'centerpiece'],
    images: [aquariumImages.fish[2], aquariumImages.fish[3]],
    variants: [
      { id: 'v3-1', name: '3-4 inches', price: 1999, stock: 10 },
      { id: 'v3-2', name: '5-6 inches', price: 3499, stock: 6 },
    ],
    reviews: generateReviews(3),
    rating: 4.7,
    reviewCount: 156,
    stock: 16,
    sku: 'LF-003',
    brand: 'Cloning Aqua Pets',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2024-01-20',
  },
  {
    id: '4',
    name: 'Halfmoon Betta - Galaxy',
    slug: 'halfmoon-betta-galaxy',
    description: 'Magnificent Galaxy Halfmoon Betta with stunning 180-degree tail spread. Deep blue body with white speckles resembling a galaxy.',
    shortDescription: 'Premium Galaxy Halfmoon Betta',
    price: 599,
    compareAtPrice: 799,
    category: 'Live Fish',
    subcategory: 'Betta',
    tags: ['betta', 'halfmoon', 'galaxy', 'siamese-fighter'],
    images: [aquariumImages.fish[3], aquariumImages.fish[4]],
    variants: [
      { id: 'v4-1', name: 'Male', price: 599, stock: 15 },
      { id: 'v4-2', name: 'Female', price: 349, stock: 20 },
    ],
    reviews: generateReviews(6),
    rating: 4.9,
    reviewCount: 312,
    stock: 35,
    sku: 'LF-004',
    brand: 'Cloning Aqua Pets',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isOnSale: true,
    petType: 'fish',
    createdAt: '2023-12-10',
  },
  {
    id: '5',
    name: 'L-046 Zebra Pleco',
    slug: 'l046-zebra-pleco',
    description: 'Rare and exotic L-046 Zebra Pleco from Brazil. Stunning black and white striped pattern. A true collectors item.',
    shortDescription: 'Rare Zebra Pleco L-046',
    price: 4999,
    category: 'Live Fish',
    subcategory: 'Plecos',
    tags: ['pleco', 'zebra', 'rare', 'catfish'],
    images: [aquariumImages.fish[4], aquariumImages.fish[0]],
    variants: [
      { id: 'v5-1', name: '2-3 inches', price: 4999, stock: 5 },
      { id: 'v5-2', name: '3-4 inches', price: 7999, stock: 3 },
    ],
    reviews: generateReviews(4),
    rating: 4.6,
    reviewCount: 78,
    stock: 8,
    sku: 'LF-005',
    brand: 'Cloning Aqua Pets',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2024-02-15',
  },
  {
    id: '6',
    name: 'Crystal Red Shrimp - Grade S',
    slug: 'crystal-red-shrimp-grade-s',
    description: 'High grade Crystal Red Shrimp with intense red and white coloration. Perfect for planted tanks and shrimp breeding.',
    shortDescription: 'Grade S Crystal Red Shrimp',
    price: 199,
    compareAtPrice: 249,
    category: 'Live Fish',
    subcategory: 'Shrimp',
    tags: ['shrimp', 'crystal-red', 'planted-tank', 'invertebrate'],
    images: [aquariumImages.fish[0], aquariumImages.fish[1]],
    variants: [
      { id: 'v6-1', name: '5 Shrimp', price: 199, stock: 30 },
      { id: 'v6-2', name: '10 Shrimp', price: 349, stock: 20 },
      { id: 'v6-3', name: '20 Shrimp', price: 599, stock: 10 },
    ],
    reviews: generateReviews(7),
    rating: 4.5,
    reviewCount: 423,
    stock: 60,
    sku: 'LF-006',
    brand: 'Cloning Aqua Pets',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: true,
    petType: 'fish',
    createdAt: '2023-11-20',
  },
  {
    id: '7',
    name: 'Blue Crayfish / Blue Lobster',
    slug: 'blue-crayfish-lobster',
    description: 'Striking electric blue crayfish. Hardy and interesting to watch. Great conversation starter for any aquarium.',
    shortDescription: 'Electric Blue Crayfish',
    price: 449,
    category: 'Live Fish',
    subcategory: 'Shrimp',
    tags: ['crayfish', 'lobster', 'blue', 'invertebrate'],
    images: [aquariumImages.fish[1], aquariumImages.fish[2]],
    variants: [],
    reviews: generateReviews(5),
    rating: 4.7,
    reviewCount: 187,
    stock: 25,
    sku: 'LF-007',
    brand: 'Cloning Aqua Pets',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2024-01-25',
  },
  {
    id: '8',
    name: 'Neon Tetra School (10 Fish)',
    slug: 'neon-tetra-school',
    description: 'Classic neon tetras with their signature blue and red stripe. Perfect schooling fish for planted community tanks.',
    shortDescription: 'School of 10 Neon Tetras',
    price: 249,
    compareAtPrice: 299,
    category: 'Live Fish',
    subcategory: 'Tetras',
    tags: ['tetra', 'neon', 'schooling', 'community'],
    images: [aquariumImages.fish[2], aquariumImages.fish[3]],
    variants: [
      { id: 'v8-1', name: '10 Fish', price: 249, stock: 50 },
      { id: 'v8-2', name: '20 Fish', price: 449, stock: 30 },
      { id: 'v8-3', name: '50 Fish', price: 999, stock: 15 },
    ],
    reviews: generateReviews(8),
    rating: 4.4,
    reviewCount: 556,
    stock: 95,
    sku: 'LF-008',
    brand: 'Cloning Aqua Pets',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: true,
    petType: 'fish',
    createdAt: '2023-10-15',
  },
  // Tanks & Equipment (9-20)
  {
    id: '9',
    name: 'Ultra Clear Glass Tank - 60cm',
    slug: 'ultra-clear-glass-tank-60cm',
    description: 'Premium ultra-clear low-iron glass aquarium. Crystal clear viewing with minimal green tint. Perfect for aquascaping.',
    shortDescription: '60cm Ultra Clear Aquarium',
    price: 4999,
    compareAtPrice: 5999,
    category: 'Tanks',
    subcategory: 'Glass Tanks',
    tags: ['tank', 'ultra-clear', 'aquascape', 'rimless'],
    images: [aquariumImages.tanks[0], aquariumImages.tanks[1]],
    variants: [
      { id: 'v9-1', name: '60x30x36cm (65L)', price: 4999, stock: 15 },
      { id: 'v9-2', name: '90x45x45cm (180L)', price: 8999, stock: 10 },
      { id: 'v9-3', name: '120x50x50cm (300L)', price: 14999, stock: 5 },
    ],
    reviews: generateReviews(5),
    rating: 4.8,
    reviewCount: 234,
    stock: 30,
    sku: 'TK-001',
    brand: 'ADA',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: true,
    petType: 'fish',
    createdAt: '2023-09-01',
  },
  {
    id: '10',
    name: 'SUNSUN Canister Filter HW-704B',
    slug: 'sunsun-canister-filter-hw704b',
    description: 'Powerful external canister filter with UV sterilizer. 4-stage filtration for crystal clear water. Suitable for tanks up to 500L.',
    shortDescription: 'External canister filter with UV',
    price: 5499,
    category: 'Equipment',
    subcategory: 'Filters',
    tags: ['filter', 'canister', 'sunsun', 'uv-sterilizer'],
    images: [aquariumImages.equipment[0], aquariumImages.equipment[1]],
    variants: [
      { id: 'v10-1', name: 'HW-704B (500L)', price: 5499, stock: 20 },
      { id: 'v10-2', name: 'HW-703B (400L)', price: 4499, stock: 25 },
      { id: 'v10-3', name: 'HW-702B (300L)', price: 3499, stock: 30 },
    ],
    reviews: generateReviews(6),
    rating: 4.7,
    reviewCount: 445,
    stock: 75,
    sku: 'EQ-001',
    brand: 'SUNSUN',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-07-20',
  },
  {
    id: '11',
    name: 'Chihiros WRGB II LED Light',
    slug: 'chihiros-wrgb-ii-led',
    description: 'Professional planted tank LED with full spectrum RGB. App-controlled with sunrise/sunset simulation. Perfect for high-tech planted tanks.',
    shortDescription: 'Premium RGB LED for planted tanks',
    price: 8999,
    compareAtPrice: 10999,
    category: 'Equipment',
    subcategory: 'Lighting',
    tags: ['led', 'chihiros', 'planted-tank', 'rgb'],
    images: [aquariumImages.equipment[1], aquariumImages.tanks[0]],
    variants: [
      { id: 'v11-1', name: '30cm', price: 5999, stock: 15 },
      { id: 'v11-2', name: '45cm', price: 7499, stock: 12 },
      { id: 'v11-3', name: '60cm', price: 8999, stock: 10 },
      { id: 'v11-4', name: '90cm', price: 12999, stock: 8 },
    ],
    reviews: generateReviews(5),
    rating: 4.9,
    reviewCount: 312,
    stock: 45,
    sku: 'EQ-002',
    brand: 'Chihiros',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isOnSale: true,
    petType: 'fish',
    createdAt: '2024-02-10',
  },
  {
    id: '12',
    name: 'Aquarium Heater - 300W',
    slug: 'aquarium-heater-300w',
    description: 'Submersible aquarium heater with precise temperature control. Shatterproof glass with auto shut-off safety feature.',
    shortDescription: 'Adjustable submersible heater',
    price: 899,
    category: 'Equipment',
    subcategory: 'Heaters',
    tags: ['heater', 'submersible', 'temperature', 'tropical'],
    images: [aquariumImages.equipment[0], aquariumImages.tanks[1]],
    variants: [
      { id: 'v12-1', name: '100W (50L)', price: 599, stock: 40 },
      { id: 'v12-2', name: '200W (100L)', price: 749, stock: 35 },
      { id: 'v12-3', name: '300W (150L)', price: 899, stock: 30 },
      { id: 'v12-4', name: '500W (250L)', price: 1199, stock: 20 },
    ],
    reviews: generateReviews(4),
    rating: 4.6,
    reviewCount: 223,
    stock: 125,
    sku: 'EQ-003',
    brand: 'RS Electrical',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-06-15',
  },
  {
    id: '13',
    name: 'CO2 System Complete Kit',
    slug: 'co2-system-complete-kit',
    description: 'Complete CO2 system with regulator, solenoid, bubble counter, and diffuser. Essential for lush planted aquariums.',
    shortDescription: 'Complete planted tank CO2 kit',
    price: 6999,
    compareAtPrice: 8499,
    category: 'Equipment',
    subcategory: 'CO2 Systems',
    tags: ['co2', 'planted-tank', 'regulator', 'diffuser'],
    images: [aquariumImages.equipment[1], aquariumImages.plants[0]],
    variants: [
      { id: 'v13-1', name: 'Standard Kit', price: 6999, stock: 15 },
      { id: 'v13-2', name: 'Pro Kit with Timer', price: 8999, stock: 10 },
    ],
    reviews: generateReviews(5),
    rating: 4.8,
    reviewCount: 178,
    stock: 25,
    sku: 'EQ-004',
    brand: 'Chihiros',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: true,
    petType: 'fish',
    createdAt: '2023-05-10',
  },
  {
    id: '14',
    name: 'Sponge Filter - Double',
    slug: 'sponge-filter-double',
    description: 'Bio sponge filter ideal for shrimp tanks and breeding setups. Gentle filtration safe for fry. Air pump operated.',
    shortDescription: 'Double bio sponge filter',
    price: 349,
    category: 'Equipment',
    subcategory: 'Filters',
    tags: ['filter', 'sponge', 'shrimp-safe', 'breeding'],
    images: [aquariumImages.equipment[0], aquariumImages.fish[0]],
    variants: [
      { id: 'v14-1', name: 'Small (30L)', price: 199, stock: 60 },
      { id: 'v14-2', name: 'Medium (60L)', price: 279, stock: 50 },
      { id: 'v14-3', name: 'Large (100L)', price: 349, stock: 40 },
    ],
    reviews: generateReviews(7),
    rating: 4.5,
    reviewCount: 567,
    stock: 150,
    sku: 'EQ-005',
    brand: 'Sobo',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-04-20',
  },
  {
    id: '15',
    name: 'Air Pump - Dual Outlet',
    slug: 'air-pump-dual-outlet',
    description: 'Quiet dual outlet air pump with adjustable flow. Powers multiple airstones or sponge filters simultaneously.',
    shortDescription: 'Quiet dual outlet air pump',
    price: 699,
    category: 'Equipment',
    subcategory: 'Air Pumps',
    tags: ['air-pump', 'dual-outlet', 'quiet', 'aeration'],
    images: [aquariumImages.equipment[1], aquariumImages.tanks[2]],
    variants: [
      { id: 'v15-1', name: 'Single Outlet', price: 399, stock: 45 },
      { id: 'v15-2', name: 'Dual Outlet', price: 699, stock: 35 },
      { id: 'v15-3', name: 'Quad Outlet', price: 999, stock: 25 },
    ],
    reviews: generateReviews(4),
    rating: 4.4,
    reviewCount: 289,
    stock: 105,
    sku: 'EQ-006',
    brand: 'Boyu',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-08-15',
  },
  // Plants & Decor (16-30)
  {
    id: '16',
    name: 'Monte Carlo Tissue Culture',
    slug: 'monte-carlo-tissue-culture',
    description: 'Pest-free tissue culture Monte Carlo carpeting plant. Creates beautiful lush green carpet. Medium difficulty.',
    shortDescription: 'Carpeting plant - Monte Carlo',
    price: 299,
    compareAtPrice: 399,
    category: 'Plants',
    subcategory: 'Carpeting',
    tags: ['plant', 'carpet', 'tissue-culture', 'monte-carlo'],
    images: [aquariumImages.plants[0], aquariumImages.plants[1]],
    variants: [],
    reviews: generateReviews(5),
    rating: 4.7,
    reviewCount: 334,
    stock: 80,
    sku: 'PL-001',
    brand: 'Tropica',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: true,
    petType: 'fish',
    createdAt: '2023-11-01',
  },
  {
    id: '17',
    name: 'Bucephalandra Green Wavy',
    slug: 'bucephalandra-green-wavy',
    description: 'Beautiful Bucephalandra with unique wavy leaves. Slow growing, attaches to hardscape. Low maintenance.',
    shortDescription: 'Premium Bucephalandra variety',
    price: 449,
    category: 'Plants',
    subcategory: 'Epiphyte',
    tags: ['plant', 'bucephalandra', 'rare', 'hardscape'],
    images: [aquariumImages.plants[1], aquariumImages.plants[0]],
    variants: [],
    reviews: generateReviews(4),
    rating: 4.8,
    reviewCount: 198,
    stock: 45,
    sku: 'PL-002',
    brand: 'Tropica',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2024-01-30',
  },
  {
    id: '18',
    name: 'Java Moss Portion',
    slug: 'java-moss-portion',
    description: 'Easy to grow Java Moss. Perfect for shrimp tanks and breeding setups. Attaches to wood and rocks.',
    shortDescription: 'Easy Java Moss for aquascaping',
    price: 149,
    category: 'Plants',
    subcategory: 'Moss',
    tags: ['moss', 'java', 'easy', 'beginner'],
    images: [aquariumImages.plants[0], aquariumImages.fish[0]],
    variants: [
      { id: 'v18-1', name: 'Small Portion', price: 149, stock: 100 },
      { id: 'v18-2', name: 'Large Portion', price: 249, stock: 60 },
    ],
    reviews: generateReviews(6),
    rating: 4.6,
    reviewCount: 412,
    stock: 160,
    sku: 'PL-003',
    brand: 'Cloning Aqua Pets',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-09-15',
  },
  {
    id: '19',
    name: 'Malaysian Driftwood - Large',
    slug: 'malaysian-driftwood-large',
    description: 'Natural Malaysian driftwood with beautiful branch structure. Pre-treated and ready to use. Perfect for aquascaping.',
    shortDescription: 'Natural aquascaping driftwood',
    price: 1299,
    category: 'Decor',
    subcategory: 'Driftwood',
    tags: ['driftwood', 'malaysian', 'natural', 'aquascape'],
    images: [aquariumImages.tanks[1], aquariumImages.plants[1]],
    variants: [
      { id: 'v19-1', name: 'Small (15-20cm)', price: 499, stock: 30 },
      { id: 'v19-2', name: 'Medium (25-35cm)', price: 899, stock: 20 },
      { id: 'v19-3', name: 'Large (40-50cm)', price: 1299, stock: 15 },
    ],
    reviews: generateReviews(5),
    rating: 4.7,
    reviewCount: 267,
    stock: 65,
    sku: 'DC-001',
    brand: 'Cloning Aqua Pets',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-08-01',
  },
  {
    id: '20',
    name: 'Dragon Stone - 5kg',
    slug: 'dragon-stone-5kg',
    description: 'Premium Dragon Stone (Ohko Stone) with unique texture. Perfect for Iwagumi and nature aquascapes.',
    shortDescription: 'Aquascaping Dragon Stone',
    price: 999,
    category: 'Decor',
    subcategory: 'Rocks',
    tags: ['rock', 'dragon-stone', 'ohko', 'iwagumi'],
    images: [aquariumImages.tanks[2], aquariumImages.tanks[0]],
    variants: [
      { id: 'v20-1', name: '2kg', price: 499, stock: 40 },
      { id: 'v20-2', name: '5kg', price: 999, stock: 25 },
      { id: 'v20-3', name: '10kg', price: 1799, stock: 15 },
    ],
    reviews: generateReviews(4),
    rating: 4.5,
    reviewCount: 189,
    stock: 80,
    sku: 'DC-002',
    brand: 'Cloning Aqua Pets',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2024-02-05',
  },
  {
    id: '21',
    name: 'ADA Aqua Soil Amazonia II',
    slug: 'ada-aqua-soil-amazonia-2',
    description: 'Premium planted tank substrate from ADA. Rich in nutrients for optimal plant growth. Lowers pH for tropical fish.',
    shortDescription: 'Premium planted tank substrate',
    price: 2499,
    category: 'Decor',
    subcategory: 'Substrate',
    tags: ['substrate', 'ada', 'planted-tank', 'soil'],
    images: [aquariumImages.plants[0], aquariumImages.tanks[0]],
    variants: [
      { id: 'v21-1', name: '3L', price: 1299, stock: 30 },
      { id: 'v21-2', name: '9L', price: 2499, stock: 20 },
    ],
    reviews: generateReviews(7),
    rating: 4.9,
    reviewCount: 456,
    stock: 50,
    sku: 'DC-003',
    brand: 'ADA',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-06-10',
  },
  {
    id: '22',
    name: 'Sand Fall Decoration',
    slug: 'sand-fall-decoration',
    description: 'Mesmerizing sand waterfall decoration. Creates underwater sand fall illusion. Includes air pump connector.',
    shortDescription: 'Sand waterfall decoration',
    price: 1499,
    compareAtPrice: 1999,
    category: 'Decor',
    subcategory: 'Ornaments',
    tags: ['decoration', 'sand-fall', 'unique', 'ornament'],
    images: [aquariumImages.tanks[1], aquariumImages.equipment[0]],
    variants: [
      { id: 'v22-1', name: 'Small', price: 999, stock: 25 },
      { id: 'v22-2', name: 'Large', price: 1499, stock: 15 },
    ],
    reviews: generateReviews(5),
    rating: 4.4,
    reviewCount: 234,
    stock: 40,
    sku: 'DC-004',
    brand: 'Bluepet',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: true,
    petType: 'fish',
    createdAt: '2024-01-15',
  },
  // Fish Food & Care (23-35)
  {
    id: '23',
    name: 'Premium Betta Pellets',
    slug: 'premium-betta-pellets',
    description: 'High protein floating pellets specially formulated for Betta fish. Enhances color and promotes health.',
    shortDescription: 'Color-enhancing Betta food',
    price: 299,
    category: 'Food',
    subcategory: 'Pellets',
    tags: ['food', 'betta', 'pellets', 'color-enhancing'],
    images: [aquariumImages.fish[3], aquariumImages.equipment[0]],
    variants: [
      { id: 'v23-1', name: '20g', price: 149, stock: 80 },
      { id: 'v23-2', name: '50g', price: 299, stock: 60 },
    ],
    reviews: generateReviews(5),
    rating: 4.6,
    reviewCount: 345,
    stock: 140,
    sku: 'FD-001',
    brand: 'Hikari',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-10-20',
  },
  {
    id: '24',
    name: 'Tropical Fish Flakes',
    slug: 'tropical-fish-flakes',
    description: 'Premium tropical fish flakes with spirulina. Balanced nutrition for all tropical community fish.',
    shortDescription: 'Complete tropical fish food',
    price: 399,
    category: 'Food',
    subcategory: 'Flakes',
    tags: ['food', 'flakes', 'tropical', 'community'],
    images: [aquariumImages.fish[0], aquariumImages.fish[1]],
    variants: [
      { id: 'v24-1', name: '50g', price: 199, stock: 70 },
      { id: 'v24-2', name: '100g', price: 349, stock: 50 },
      { id: 'v24-3', name: '200g', price: 599, stock: 30 },
    ],
    reviews: generateReviews(6),
    rating: 4.5,
    reviewCount: 412,
    stock: 150,
    sku: 'FD-002',
    brand: 'Tetra',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-07-01',
  },
  {
    id: '25',
    name: 'Shrimp Food - Snowflake',
    slug: 'shrimp-food-snowflake',
    description: 'Premium soybean-based snowflake food for shrimp. Rich in protein and minerals. Safe for all shrimp species.',
    shortDescription: 'Premium shrimp snowflake food',
    price: 249,
    category: 'Food',
    subcategory: 'Shrimp Food',
    tags: ['food', 'shrimp', 'snowflake', 'protein'],
    images: [aquariumImages.fish[0], aquariumImages.plants[0]],
    variants: [
      { id: 'v25-1', name: '30g', price: 249, stock: 60 },
      { id: 'v25-2', name: '60g', price: 399, stock: 40 },
    ],
    reviews: generateReviews(5),
    rating: 4.7,
    reviewCount: 267,
    stock: 100,
    sku: 'FD-003',
    brand: 'GlasGarten',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2024-01-28',
  },
  {
    id: '26',
    name: 'API Master Test Kit',
    slug: 'api-master-test-kit',
    description: 'Complete freshwater test kit. Tests pH, ammonia, nitrite, and nitrate. Essential for maintaining water quality.',
    shortDescription: 'Complete water test kit',
    price: 1999,
    compareAtPrice: 2499,
    category: 'Care',
    subcategory: 'Testing',
    tags: ['test-kit', 'water-quality', 'api', 'freshwater'],
    images: [aquariumImages.equipment[0], aquariumImages.tanks[0]],
    variants: [],
    reviews: generateReviews(6),
    rating: 4.8,
    reviewCount: 567,
    stock: 40,
    sku: 'CR-001',
    brand: 'API',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: true,
    petType: 'fish',
    createdAt: '2023-05-15',
  },
  {
    id: '27',
    name: 'Seachem Prime - 500ml',
    slug: 'seachem-prime-500ml',
    description: 'Complete water conditioner. Removes chlorine, chloramine, and detoxifies ammonia. Most concentrated formula available.',
    shortDescription: 'Premium water conditioner',
    price: 899,
    category: 'Care',
    subcategory: 'Conditioners',
    tags: ['conditioner', 'seachem', 'chlorine', 'ammonia'],
    images: [aquariumImages.equipment[1], aquariumImages.tanks[1]],
    variants: [
      { id: 'v27-1', name: '100ml', price: 349, stock: 70 },
      { id: 'v27-2', name: '250ml', price: 599, stock: 50 },
      { id: 'v27-3', name: '500ml', price: 899, stock: 35 },
    ],
    reviews: generateReviews(7),
    rating: 4.9,
    reviewCount: 678,
    stock: 155,
    sku: 'CR-002',
    brand: 'Seachem',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-12-10',
  },
  {
    id: '28',
    name: 'Plant Fertilizer - Flourish',
    slug: 'plant-fertilizer-flourish',
    description: 'Comprehensive plant supplement with essential trace elements. Promotes lush plant growth in planted aquariums.',
    shortDescription: 'Complete plant fertilizer',
    price: 699,
    category: 'Care',
    subcategory: 'Fertilizers',
    tags: ['fertilizer', 'plants', 'seachem', 'trace-elements'],
    images: [aquariumImages.plants[0], aquariumImages.plants[1]],
    variants: [
      { id: 'v28-1', name: '100ml', price: 399, stock: 50 },
      { id: 'v28-2', name: '250ml', price: 699, stock: 35 },
      { id: 'v28-3', name: '500ml', price: 999, stock: 25 },
    ],
    reviews: generateReviews(5),
    rating: 4.6,
    reviewCount: 345,
    stock: 110,
    sku: 'CR-003',
    brand: 'Seachem',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-11-15',
  },
  {
    id: '29',
    name: 'Ich Treatment Medicine',
    slug: 'ich-treatment-medicine',
    description: 'Fast-acting treatment for Ich (white spot disease). Safe for all tropical fish. Treats up to 200L.',
    shortDescription: 'White spot disease treatment',
    price: 349,
    category: 'Care',
    subcategory: 'Medicine',
    tags: ['medicine', 'ich', 'treatment', 'disease'],
    images: [aquariumImages.equipment[0], aquariumImages.fish[2]],
    variants: [],
    reviews: generateReviews(4),
    rating: 4.5,
    reviewCount: 234,
    stock: 60,
    sku: 'CR-004',
    brand: 'API',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-10-01',
  },
  {
    id: '30',
    name: 'Aquarium Salt - 1kg',
    slug: 'aquarium-salt-1kg',
    description: 'Pure aquarium salt for freshwater fish. Promotes fish health and aids in disease recovery. Easy to dissolve.',
    shortDescription: 'Freshwater aquarium salt',
    price: 199,
    category: 'Care',
    subcategory: 'Salt',
    tags: ['salt', 'freshwater', 'health', 'recovery'],
    images: [aquariumImages.equipment[1], aquariumImages.fish[0]],
    variants: [
      { id: 'v30-1', name: '500g', price: 129, stock: 80 },
      { id: 'v30-2', name: '1kg', price: 199, stock: 60 },
      { id: 'v30-3', name: '5kg', price: 699, stock: 30 },
    ],
    reviews: generateReviews(5),
    rating: 4.4,
    reviewCount: 289,
    stock: 170,
    sku: 'CR-005',
    brand: 'API',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-08-20',
  },
  // Accessories & Tools (31-40)
  {
    id: '31',
    name: 'Aquascaping Tool Set',
    slug: 'aquascaping-tool-set',
    description: 'Professional stainless steel aquascaping tools. Includes scissors, tweezers, and spatula. Essential for planted tanks.',
    shortDescription: 'Professional aquascaping tools',
    price: 1499,
    compareAtPrice: 1999,
    category: 'Accessories',
    subcategory: 'Tools',
    tags: ['tools', 'aquascaping', 'scissors', 'tweezers'],
    images: [aquariumImages.equipment[0], aquariumImages.plants[0]],
    variants: [
      { id: 'v31-1', name: '3-Piece Set', price: 999, stock: 30 },
      { id: 'v31-2', name: '5-Piece Set', price: 1499, stock: 20 },
    ],
    reviews: generateReviews(6),
    rating: 4.7,
    reviewCount: 345,
    stock: 50,
    sku: 'AC-001',
    brand: 'Chihiros',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: true,
    petType: 'fish',
    createdAt: '2023-07-15',
  },
  {
    id: '32',
    name: 'Fish Net - Fine Mesh',
    slug: 'fish-net-fine-mesh',
    description: 'Soft fine mesh fish net. Gentle on fish fins and scales. Sturdy handle with comfortable grip.',
    shortDescription: 'Gentle fine mesh fish net',
    price: 149,
    category: 'Accessories',
    subcategory: 'Nets',
    tags: ['net', 'fish', 'fine-mesh', 'gentle'],
    images: [aquariumImages.equipment[1], aquariumImages.fish[1]],
    variants: [
      { id: 'v32-1', name: 'Small (3 inch)', price: 99, stock: 80 },
      { id: 'v32-2', name: 'Medium (5 inch)', price: 149, stock: 60 },
      { id: 'v32-3', name: 'Large (8 inch)', price: 199, stock: 40 },
    ],
    reviews: generateReviews(4),
    rating: 4.5,
    reviewCount: 234,
    stock: 180,
    sku: 'AC-002',
    brand: 'Boyu',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-06-20',
  },
  {
    id: '33',
    name: 'Magnetic Glass Cleaner',
    slug: 'magnetic-glass-cleaner',
    description: 'Powerful floating magnetic cleaner. Removes algae without getting hands wet. Includes scraper blade.',
    shortDescription: 'Magnetic algae cleaner',
    price: 599,
    category: 'Accessories',
    subcategory: 'Cleaning',
    tags: ['cleaner', 'magnetic', 'algae', 'glass'],
    images: [aquariumImages.tanks[0], aquariumImages.equipment[0]],
    variants: [
      { id: 'v33-1', name: 'Small (up to 6mm)', price: 399, stock: 40 },
      { id: 'v33-2', name: 'Medium (up to 10mm)', price: 599, stock: 30 },
      { id: 'v33-3', name: 'Large (up to 15mm)', price: 899, stock: 20 },
    ],
    reviews: generateReviews(5),
    rating: 4.6,
    reviewCount: 312,
    stock: 90,
    sku: 'AC-003',
    brand: 'Flipper',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-05-10',
  },
  {
    id: '34',
    name: 'Digital Thermometer',
    slug: 'digital-thermometer',
    description: 'Accurate digital thermometer with LCD display. Easy to read with suction cup mount. Shows Celsius and Fahrenheit.',
    shortDescription: 'Digital aquarium thermometer',
    price: 249,
    category: 'Accessories',
    subcategory: 'Monitoring',
    tags: ['thermometer', 'digital', 'temperature', 'lcd'],
    images: [aquariumImages.equipment[1], aquariumImages.tanks[1]],
    variants: [],
    reviews: generateReviews(4),
    rating: 4.4,
    reviewCount: 278,
    stock: 75,
    sku: 'AC-004',
    brand: 'Sobo',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-09-10',
  },
  {
    id: '35',
    name: 'Feeding Ring',
    slug: 'feeding-ring',
    description: 'Floating feeding ring keeps food in one area. Reduces waste and keeps tank cleaner. Includes suction cup.',
    shortDescription: 'Floating feeding station',
    price: 99,
    category: 'Accessories',
    subcategory: 'Feeding',
    tags: ['feeding', 'ring', 'floating', 'clean'],
    images: [aquariumImages.fish[0], aquariumImages.tanks[0]],
    variants: [],
    reviews: generateReviews(5),
    rating: 4.3,
    reviewCount: 189,
    stock: 100,
    sku: 'AC-005',
    brand: 'Cloning Aqua Pets',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-07-05',
  },
  // More Products (36-50)
  {
    id: '36',
    name: 'Automatic Fish Feeder',
    slug: 'automatic-fish-feeder',
    description: 'Programmable automatic feeder with LCD display. Up to 4 feeding times per day. Battery operated with low battery indicator.',
    shortDescription: 'Smart automatic fish feeder',
    price: 1299,
    compareAtPrice: 1599,
    category: 'Accessories',
    subcategory: 'Feeding',
    tags: ['feeder', 'automatic', 'timer', 'smart'],
    images: [aquariumImages.equipment[0], aquariumImages.tanks[2]],
    variants: [],
    reviews: generateReviews(5),
    rating: 4.5,
    reviewCount: 234,
    stock: 35,
    sku: 'AC-006',
    brand: 'Jebao',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: true,
    petType: 'fish',
    createdAt: '2024-02-08',
  },
  {
    id: '37',
    name: 'Aquarium Chiller - 1/4 HP',
    slug: 'aquarium-chiller-quarter-hp',
    description: 'Efficient aquarium chiller for tropical climates. Keeps water cool during summer. Suitable for tanks up to 300L.',
    shortDescription: 'Aquarium cooling chiller',
    price: 12999,
    category: 'Equipment',
    subcategory: 'Chillers',
    tags: ['chiller', 'cooling', 'summer', 'temperature'],
    images: [aquariumImages.equipment[1], aquariumImages.tanks[0]],
    variants: [
      { id: 'v37-1', name: '1/10 HP (up to 100L)', price: 7999, stock: 10 },
      { id: 'v37-2', name: '1/4 HP (up to 300L)', price: 12999, stock: 8 },
      { id: 'v37-3', name: '1/2 HP (up to 500L)', price: 18999, stock: 5 },
    ],
    reviews: generateReviews(4),
    rating: 4.7,
    reviewCount: 145,
    stock: 23,
    sku: 'EQ-007',
    brand: 'Hailea',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-11-25',
  },
  {
    id: '38',
    name: 'Wavemaker Pump',
    slug: 'wavemaker-pump',
    description: 'Controllable wavemaker for natural water circulation. Creates reef-like water movement. Energy efficient motor.',
    shortDescription: 'Aquarium wavemaker pump',
    price: 1999,
    category: 'Equipment',
    subcategory: 'Pumps',
    tags: ['wavemaker', 'pump', 'circulation', 'reef'],
    images: [aquariumImages.equipment[0], aquariumImages.tanks[1]],
    variants: [
      { id: 'v38-1', name: '3000 L/H', price: 1499, stock: 25 },
      { id: 'v38-2', name: '6000 L/H', price: 1999, stock: 20 },
      { id: 'v38-3', name: '12000 L/H', price: 2999, stock: 12 },
    ],
    reviews: generateReviews(5),
    rating: 4.6,
    reviewCount: 267,
    stock: 57,
    sku: 'EQ-008',
    brand: 'Jebao',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2024-01-18',
  },
  {
    id: '39',
    name: 'Anubias Nana on Driftwood',
    slug: 'anubias-nana-driftwood',
    description: 'Beautiful Anubias Nana pre-attached to natural driftwood. Ready to place in your aquarium. Low light, easy care.',
    shortDescription: 'Anubias on driftwood decor',
    price: 699,
    category: 'Plants',
    subcategory: 'Anubias',
    tags: ['plant', 'anubias', 'driftwood', 'easy'],
    images: [aquariumImages.plants[1], aquariumImages.tanks[1]],
    variants: [
      { id: 'v39-1', name: 'Small', price: 449, stock: 30 },
      { id: 'v39-2', name: 'Medium', price: 699, stock: 20 },
      { id: 'v39-3', name: 'Large', price: 999, stock: 10 },
    ],
    reviews: generateReviews(4),
    rating: 4.8,
    reviewCount: 189,
    stock: 60,
    sku: 'PL-004',
    brand: 'Cloning Aqua Pets',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-10-05',
  },
  {
    id: '40',
    name: 'Rotala Rotundifolia Bunch',
    slug: 'rotala-rotundifolia-bunch',
    description: 'Beautiful pink-red stem plant for background planting. Fast growing with proper CO2 and lighting. Easy to propagate.',
    shortDescription: 'Pink stem plant bunch',
    price: 199,
    category: 'Plants',
    subcategory: 'Stem Plants',
    tags: ['plant', 'rotala', 'stem', 'red'],
    images: [aquariumImages.plants[0], aquariumImages.plants[1]],
    variants: [],
    reviews: generateReviews(5),
    rating: 4.5,
    reviewCount: 234,
    stock: 80,
    sku: 'PL-005',
    brand: 'Cloning Aqua Pets',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-09-20',
  },
  {
    id: '41',
    name: 'Koi Food Premium Pellets',
    slug: 'koi-food-premium-pellets',
    description: 'High quality koi food with color enhancers. Floating pellets for easy feeding. Rich in vitamins and minerals.',
    shortDescription: 'Premium koi fish food',
    price: 599,
    category: 'Food',
    subcategory: 'Koi Food',
    tags: ['food', 'koi', 'pellets', 'color-enhancing'],
    images: [aquariumImages.fish[1], aquariumImages.equipment[0]],
    variants: [
      { id: 'v41-1', name: '500g', price: 599, stock: 50 },
      { id: 'v41-2', name: '1kg', price: 999, stock: 35 },
      { id: 'v41-3', name: '5kg', price: 3999, stock: 15 },
    ],
    reviews: generateReviews(5),
    rating: 4.7,
    reviewCount: 278,
    stock: 100,
    sku: 'FD-004',
    brand: 'Hikari',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-06-25',
  },
  {
    id: '42',
    name: 'Discus Fish Food',
    slug: 'discus-fish-food-granules',
    description: 'Specially formulated sinking granules for Discus fish. High protein with essential vitamins. Promotes vibrant colors.',
    shortDescription: 'Premium Discus food granules',
    price: 499,
    category: 'Food',
    subcategory: 'Granules',
    tags: ['food', 'discus', 'granules', 'sinking'],
    images: [aquariumImages.fish[2], aquariumImages.fish[3]],
    variants: [
      { id: 'v42-1', name: '100g', price: 499, stock: 45 },
      { id: 'v42-2', name: '250g', price: 999, stock: 30 },
    ],
    reviews: generateReviews(4),
    rating: 4.6,
    reviewCount: 189,
    stock: 75,
    sku: 'FD-005',
    brand: 'Sera',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-10-15',
  },
  {
    id: '43',
    name: 'Airline Tubing - 5m',
    slug: 'airline-tubing-5m',
    description: 'Flexible silicone airline tubing. Crystal clear and kink resistant. Compatible with standard air pumps.',
    shortDescription: 'Flexible airline tube',
    price: 149,
    category: 'Accessories',
    subcategory: 'Tubing',
    tags: ['tubing', 'airline', 'silicone', 'air-pump'],
    images: [aquariumImages.equipment[1], aquariumImages.equipment[0]],
    variants: [
      { id: 'v43-1', name: '3m', price: 99, stock: 100 },
      { id: 'v43-2', name: '5m', price: 149, stock: 80 },
      { id: 'v43-3', name: '10m', price: 249, stock: 50 },
    ],
    reviews: generateReviews(4),
    rating: 4.4,
    reviewCount: 345,
    stock: 230,
    sku: 'AC-007',
    brand: 'Boyu',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-12-01',
  },
  {
    id: '44',
    name: 'LED Bubble Airstone',
    slug: 'led-bubble-airstone',
    description: 'Color-changing LED airstone creates beautiful bubble effect. Adds oxygen and visual appeal. Multiple colors.',
    shortDescription: 'LED light-up airstone',
    price: 299,
    category: 'Decor',
    subcategory: 'Airstones',
    tags: ['airstone', 'led', 'bubbles', 'decoration'],
    images: [aquariumImages.tanks[2], aquariumImages.equipment[1]],
    variants: [
      { id: 'v44-1', name: '4 inch', price: 299, stock: 50 },
      { id: 'v44-2', name: '8 inch', price: 449, stock: 30 },
      { id: 'v44-3', name: '12 inch', price: 599, stock: 20 },
    ],
    reviews: generateReviews(5),
    rating: 4.3,
    reviewCount: 234,
    stock: 100,
    sku: 'DC-005',
    brand: 'Bluepet',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2024-02-12',
  },
  {
    id: '45',
    name: 'Gravel Vacuum Cleaner',
    slug: 'gravel-vacuum-cleaner',
    description: 'Easy-to-use gravel cleaner for water changes. Removes debris without disturbing substrate. Various sizes available.',
    shortDescription: 'Aquarium gravel vacuum',
    price: 349,
    category: 'Accessories',
    subcategory: 'Cleaning',
    tags: ['vacuum', 'gravel', 'cleaning', 'water-change'],
    images: [aquariumImages.equipment[0], aquariumImages.tanks[0]],
    variants: [
      { id: 'v45-1', name: 'Small (up to 50L)', price: 249, stock: 45 },
      { id: 'v45-2', name: 'Medium (up to 150L)', price: 349, stock: 35 },
      { id: 'v45-3', name: 'Large (up to 300L)', price: 499, stock: 25 },
    ],
    reviews: generateReviews(6),
    rating: 4.5,
    reviewCount: 389,
    stock: 105,
    sku: 'AC-008',
    brand: 'Python',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-07-20',
  },
  {
    id: '46',
    name: 'Aquarium Background - 3D',
    slug: 'aquarium-background-3d',
    description: 'Realistic 3D aquarium background. Easy to install with aquarium-safe adhesive. Creates stunning depth effect.',
    shortDescription: '3D rocky background',
    price: 1999,
    compareAtPrice: 2499,
    category: 'Decor',
    subcategory: 'Backgrounds',
    tags: ['background', '3d', 'realistic', 'rock'],
    images: [aquariumImages.tanks[1], aquariumImages.tanks[2]],
    variants: [
      { id: 'v46-1', name: '60x40cm', price: 1299, stock: 20 },
      { id: 'v46-2', name: '90x50cm', price: 1999, stock: 15 },
      { id: 'v46-3', name: '120x60cm', price: 2999, stock: 10 },
    ],
    reviews: generateReviews(4),
    rating: 4.6,
    reviewCount: 156,
    stock: 45,
    sku: 'DC-006',
    brand: 'Juwel',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: true,
    petType: 'fish',
    createdAt: '2023-11-01',
  },
  {
    id: '47',
    name: 'Frozen Bloodworms',
    slug: 'frozen-bloodworms',
    description: 'Premium frozen bloodworms. High protein treat for all tropical fish. Individually quick frozen for freshness.',
    shortDescription: 'Frozen bloodworm cubes',
    price: 299,
    category: 'Food',
    subcategory: 'Frozen',
    tags: ['food', 'frozen', 'bloodworms', 'treat'],
    images: [aquariumImages.fish[0], aquariumImages.fish[4]],
    variants: [
      { id: 'v47-1', name: '100g', price: 299, stock: 60 },
      { id: 'v47-2', name: '250g', price: 599, stock: 40 },
    ],
    reviews: generateReviews(5),
    rating: 4.7,
    reviewCount: 423,
    stock: 100,
    sku: 'FD-006',
    brand: 'Ocean Nutrition',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-08-10',
  },
  {
    id: '48',
    name: 'Ceramic Bio Rings - 1kg',
    slug: 'ceramic-bio-rings-1kg',
    description: 'High quality porous ceramic rings for biological filtration. Maximum surface area for beneficial bacteria.',
    shortDescription: 'Ceramic filter media',
    price: 399,
    category: 'Equipment',
    subcategory: 'Filter Media',
    tags: ['media', 'ceramic', 'biological', 'filtration'],
    images: [aquariumImages.equipment[0], aquariumImages.equipment[1]],
    variants: [
      { id: 'v48-1', name: '500g', price: 249, stock: 70 },
      { id: 'v48-2', name: '1kg', price: 399, stock: 50 },
      { id: 'v48-3', name: '2kg', price: 699, stock: 30 },
    ],
    reviews: generateReviews(5),
    rating: 4.6,
    reviewCount: 345,
    stock: 150,
    sku: 'EQ-009',
    brand: 'Seachem',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-09-05',
  },
  {
    id: '49',
    name: 'Glass CO2 Diffuser',
    slug: 'glass-co2-diffuser',
    description: 'Premium glass CO2 diffuser with ceramic disc. Creates ultra-fine bubbles for maximum CO2 absorption.',
    shortDescription: 'Glass CO2 atomizer diffuser',
    price: 599,
    category: 'Equipment',
    subcategory: 'CO2 Systems',
    tags: ['co2', 'diffuser', 'glass', 'planted-tank'],
    images: [aquariumImages.plants[0], aquariumImages.equipment[1]],
    variants: [
      { id: 'v49-1', name: 'Small (up to 100L)', price: 399, stock: 40 },
      { id: 'v49-2', name: 'Medium (up to 200L)', price: 599, stock: 30 },
      { id: 'v49-3', name: 'Large (up to 400L)', price: 899, stock: 20 },
    ],
    reviews: generateReviews(4),
    rating: 4.7,
    reviewCount: 234,
    stock: 90,
    sku: 'EQ-010',
    brand: 'Chihiros',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2024-01-05',
  },
  {
    id: '50',
    name: 'Quarantine Tank Kit',
    slug: 'quarantine-tank-kit',
    description: 'Complete quarantine setup with 20L tank, sponge filter, and heater. Essential for new fish acclimation.',
    shortDescription: 'Complete quarantine setup',
    price: 1999,
    compareAtPrice: 2499,
    category: 'Tanks',
    subcategory: 'Starter Kits',
    tags: ['tank', 'quarantine', 'starter', 'complete'],
    images: [aquariumImages.tanks[2], aquariumImages.equipment[0]],
    variants: [],
    reviews: generateReviews(5),
    rating: 4.5,
    reviewCount: 178,
    stock: 25,
    sku: 'TK-002',
    brand: 'Cloning Aqua Pets',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: true,
    petType: 'fish',
    createdAt: '2024-02-01',
  },
]

// Hero Slides - Aquarium themed
export const heroSlides: HeroSlide[] = [
  {
    id: '1',
    title: 'Your Aquatic Paradise',
    subtitle: 'Premium Aquarium Supplies',
    description: 'Discover our curated collection of premium aquarium products. From exotic fish to professional equipment.',
    image: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=1920',
    ctaText: 'Shop Now',
    ctaLink: '/shop',
    secondaryCtaText: 'View Collections',
    secondaryCtaLink: '/collections',
    textPosition: 'left',
  },
  {
    id: '2',
    title: 'Exotic Live Fish',
    subtitle: 'Fresh Arrivals Weekly',
    description: 'From fancy guppies to rare plecos - find your perfect aquatic companion. Healthy fish guaranteed.',
    image: 'https://images.unsplash.com/photo-1520990059-1e21b5c78e93?w=1920',
    ctaText: 'Shop Fish',
    ctaLink: '/shop?category=fish',
    textPosition: 'center',
  },
  {
    id: '3',
    title: 'Up to 40% Off',
    subtitle: 'Mega Sale Event',
    description: 'Limited time offers on tanks, filters, and more! Dont miss these amazing deals on premium equipment.',
    image: 'https://images.unsplash.com/photo-1571752726703-5e7d1f6a986d?w=1920',
    ctaText: 'Shop Sale',
    ctaLink: '/shop?filter=sale',
    textPosition: 'right',
  },
  {
    id: '4',
    title: 'Ultra Clear Tanks',
    subtitle: 'Premium Glass Quality',
    description: 'Experience crystal clear viewing with our low-iron ultra clear aquariums. Perfect for aquascaping.',
    image: 'https://images.unsplash.com/photo-1559717201-fbb671ff56b7?w=1920',
    ctaText: 'Shop Tanks',
    ctaLink: '/shop?category=tanks',
    textPosition: 'left',
  },
  {
    id: '5',
    title: 'Planted Tank Paradise',
    subtitle: 'Complete Plant Collection',
    description: 'Transform your aquarium with lush aquatic plants. CO2 systems, lights, and fertilizers available.',
    image: 'https://images.unsplash.com/photo-1585241936939-be4099591252?w=1920',
    ctaText: 'Shop Plants',
    ctaLink: '/shop?category=plants',
    textPosition: 'center',
  },
]

// Testimonials - Aquarium enthusiasts
export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Rajesh Kumar',
    location: 'Salem, Tamil Nadu',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    petImage: 'https://images.unsplash.com/photo-1520990059-1e21b5c78e93?w=400',
    petName: 'My Discus Tank',
    rating: 5,
    content: 'Best aquarium store in Salem! The fish quality is excellent and they provide great advice on tank setup. My discus are thriving!',
  },
  {
    id: '2',
    name: 'Priya Venkatesh',
    location: 'Chennai, Tamil Nadu',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    petImage: 'https://images.unsplash.com/photo-1571752726703-5e7d1f6a986d?w=400',
    petName: 'Planted Aquascape',
    rating: 5,
    content: 'Amazing plant selection and CO2 equipment! The Chihiros lights transformed my planted tank. Highly recommend for aquascapers.',
  },
  {
    id: '3',
    name: 'Mohammed Farhan',
    location: 'Coimbatore, Tamil Nadu',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
    petImage: 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=400',
    petName: 'Koi Pond',
    rating: 5,
    content: 'Their Japanese Koi are absolutely stunning! Fast delivery and fish arrived healthy. The pond equipment is top quality too.',
  },
  {
    id: '4',
    name: 'Lakshmi Devi',
    location: 'Bangalore, Karnataka',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
    petImage: 'https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=400',
    petName: 'Community Tank',
    rating: 4,
    content: 'Great customer service and product range. The neon tetras and guppies are very healthy. Shipping was fast even to Bangalore!',
  },
  {
    id: '5',
    name: 'Arun Prakash',
    location: 'Madurai, Tamil Nadu',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
    petImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400',
    petName: 'Betta Collection',
    rating: 5,
    content: 'The halfmoon bettas here are gorgeous! Premium quality and the packaging for live fish is excellent. My go-to store now.',
  },
]

// Blog Posts - Aquarium topics
export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'Complete Guide to Setting Up Your First Planted Tank',
    slug: 'complete-guide-planted-tank-setup',
    excerpt: 'Learn everything you need to know about creating a beautiful planted aquarium - from substrate to CO2 injection.',
    content: 'Full article content about planted tank setup...',
    image: 'https://images.unsplash.com/photo-1585241936939-be4099591252?w=800',
    author: 'Dr. Rajan Aquatics',
    authorImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
    category: 'Planted Tanks',
    tags: ['planted-tank', 'aquascaping', 'beginner', 'setup'],
    publishedAt: '2024-02-15',
    readTime: 12,
  },
  {
    id: '2',
    title: 'Discus Fish Care: Tips for Healthy Kings',
    slug: 'discus-fish-care-guide',
    excerpt: 'Master the art of keeping discus fish healthy and vibrant with our comprehensive care guide.',
    content: 'Full article content about discus care...',
    image: 'https://images.unsplash.com/photo-1520990059-1e21b5c78e93?w=800',
    author: 'Kavitha Fish Expert',
    authorImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
    category: 'Fish Care',
    tags: ['discus', 'tropical-fish', 'care', 'advanced'],
    publishedAt: '2024-02-10',
    readTime: 8,
  },
  {
    id: '3',
    title: 'Best Aquarium Filters: A Complete Buying Guide',
    slug: 'best-aquarium-filters-guide',
    excerpt: 'Compare canister filters, HOB filters, and sponge filters to find the perfect filtration for your tank.',
    content: 'Full article content about filtration...',
    image: 'https://images.unsplash.com/photo-1584461049019-eb37661c7a7e?w=800',
    author: 'Tech Aquarist',
    authorImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100',
    category: 'Equipment',
    tags: ['filter', 'equipment', 'buying-guide', 'canister'],
    publishedAt: '2024-02-05',
    readTime: 10,
  },
  {
    id: '4',
    title: 'Crystal Red Shrimp: Complete Breeding Guide',
    slug: 'crystal-red-shrimp-breeding',
    excerpt: 'Learn how to successfully breed Crystal Red Shrimp and maintain a thriving shrimp colony.',
    content: 'Full article content about shrimp breeding...',
    image: 'https://images.unsplash.com/photo-1571752726703-5e7d1f6a986d?w=800',
    author: 'Shrimp Master',
    authorImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
    category: 'Shrimp Keeping',
    tags: ['shrimp', 'breeding', 'crystal-red', 'invertebrates'],
    publishedAt: '2024-01-28',
    readTime: 15,
  },
  {
    id: '5',
    title: 'Summer Aquarium Care: Keeping Fish Cool',
    slug: 'summer-aquarium-care-tips',
    excerpt: 'Essential tips to maintain optimal water temperature during hot Indian summers.',
    content: 'Full article content about summer care...',
    image: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=800',
    author: 'Dr. Rajan Aquatics',
    authorImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
    category: 'Fish Care',
    tags: ['summer', 'temperature', 'chiller', 'cooling'],
    publishedAt: '2024-01-20',
    readTime: 6,
  },
  {
    id: '6',
    title: 'Iwagumi Aquascaping: A Step-by-Step Guide',
    slug: 'iwagumi-aquascaping-guide',
    excerpt: 'Create stunning minimalist aquascapes using the Japanese Iwagumi style.',
    content: 'Full article content about Iwagumi...',
    image: 'https://images.unsplash.com/photo-1559717201-fbb671ff56b7?w=800',
    author: 'Aquascape Artist',
    authorImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100',
    category: 'Aquascaping',
    tags: ['iwagumi', 'aquascaping', 'minimalist', 'rocks'],
    publishedAt: '2024-01-15',
    readTime: 10,
  },
]

// Collections - Aquarium categories
export const collections: Collection[] = [
  { id: '1', name: 'Live Fish', slug: 'live-fish', description: 'Exotic tropical fish and rare species', image: aquariumImages.fish[0], productCount: 12 },
  { id: '2', name: 'Aquarium Tanks', slug: 'tanks', description: 'Ultra clear glass tanks for aquascaping', image: aquariumImages.tanks[0], productCount: 8 },
  { id: '3', name: 'Filters & Equipment', slug: 'equipment', description: 'Professional filtration and equipment', image: aquariumImages.equipment[0], productCount: 15 },
  { id: '4', name: 'Plants & Decor', slug: 'plants-decor', description: 'Aquatic plants and natural decor', image: aquariumImages.plants[0], productCount: 20 },
  { id: '5', name: 'Fish Food', slug: 'food', description: 'Premium nutrition for all fish', image: aquariumImages.fish[1], productCount: 10 },
  { id: '6', name: 'Water Care', slug: 'water-care', description: 'Conditioners, test kits, and treatments', image: aquariumImages.equipment[1], productCount: 12 },
]

// FAQs - Aquarium specific
export const faqs: FAQItem[] = [
  { id: '1', question: 'How do you ship live fish?', answer: 'We use specialized insulated boxes with heat/cold packs and pure oxygen bags. Fish are shipped via express courier to ensure 24-48 hour delivery.', category: 'Shipping' },
  { id: '2', question: 'What is your DOA (Dead on Arrival) policy?', answer: 'We offer full replacement or refund for any fish that arrive dead. Simply send clear photos within 2 hours of delivery.', category: 'Returns' },
  { id: '3', question: 'Do you provide aquarium setup services?', answer: 'Yes! We offer professional aquarium setup and maintenance services in Salem and nearby areas. Contact us for details.', category: 'Services' },
  { id: '4', question: 'Can I visit your store?', answer: 'Absolutely! Our store in Salem is open 7 days a week. Come see our fish and equipment in person.', category: 'Store' },
  { id: '5', question: 'Do you ship plants and equipment all over India?', answer: 'Yes, we ship equipment and plants pan-India. Live fish are currently available for select pin codes only.', category: 'Shipping' },
  { id: '6', question: 'How do I cycle a new aquarium?', answer: 'Check our blog for a complete cycling guide. We also offer beneficial bacteria products to speed up the process.', category: 'Care' },
]

// Stats - Aquarium focused
export const stats: Stat[] = [
  { id: '1', label: 'Happy Aquarists', value: 25000, suffix: '+', icon: 'heart' },
  { id: '2', label: 'Products', value: 1500, suffix: '+', icon: 'package' },
  { id: '3', label: '5-Star Reviews', value: 8000, suffix: '+', icon: 'star' },
  { id: '4', label: 'Cities We Ship To', value: 200, suffix: '+', icon: 'globe' },
]

// Helper functions
export const getProductById = (id: string): Product | undefined => products.find(p => p.id === id)
export const getProductBySlug = (slug: string): Product | undefined => products.find(p => p.slug === slug)
export const getFeaturedProducts = (): Product[] => products.filter(p => p.isFeatured)
export const getBestSellers = (): Product[] => products.filter(p => p.isBestSeller)
export const getNewArrivals = (): Product[] => products.filter(p => p.isNewArrival)
export const getOnSaleProducts = (): Product[] => products.filter(p => p.isOnSale)
export const getProductsByCategory = (category: string): Product[] => products.filter(p => p.category === category)
export const getProductsByPetType = (petType: string): Product[] => products.filter(p => p.petType === petType || p.petType === 'all')
export const searchProducts = (query: string): Product[] => {
  const lowerQuery = query.toLowerCase()
  return products.filter(p =>
    p.name.toLowerCase().includes(lowerQuery) ||
    p.description.toLowerCase().includes(lowerQuery) ||
    p.tags.some(t => t.toLowerCase().includes(lowerQuery))
  )
}
